# Makefile.in generated by automake 1.11.3 from Makefile.am.
# Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002,
# 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011 Free Software
# Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.




pkgdatadir = $(datadir)/main
pkgincludedir = $(includedir)/main
pkglibdir = $(libdir)/main
pkglibexecdir = $(libexecdir)/main
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
bin_PROGRAMS = server$(EXEEXT)
subdir = .
DIST_COMMON = README $(am__configure_deps) $(srcdir)/Makefile.am \
	$(srcdir)/Makefile.in $(srcdir)/config.h.in \
	$(top_srcdir)/configure AUTHORS COPYING ChangeLog INSTALL NEWS \
	depcomp install-sh missing
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/configure.in
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
 configure.lineno config.status.lineno
mkinstalldirs = $(install_sh) -d
CONFIG_HEADER = config.h
CONFIG_CLEAN_FILES =
CONFIG_CLEAN_VPATH_FILES =
am__installdirs = "$(DESTDIR)$(bindir)"
PROGRAMS = $(bin_PROGRAMS)
am_server_OBJECTS = main.$(OBJEXT) Single.$(OBJEXT) Config.$(OBJEXT) \
	HandleMessage.$(OBJEXT) HandleBuildHouse.$(OBJEXT) \
	HandleExercise.$(OBJEXT) HandlePuzzle.$(OBJEXT) \
	HandleCartoon.$(OBJEXT) HandleSprite.$(OBJEXT) \
	HandleClassRoom.$(OBJEXT) teacher.$(OBJEXT) \
	courseitem.$(OBJEXT) roommanager.$(OBJEXT) course.$(OBJEXT) \
	student.$(OBJEXT) game.$(OBJEXT) grade.$(OBJEXT) \
	LoginCheck.$(OBJEXT) room.$(OBJEXT) ThreadPool.$(OBJEXT) \
	database.$(OBJEXT) Evloop.$(OBJEXT) RecvTask.$(OBJEXT) \
	SendTask.$(OBJEXT) ProcessManager.$(OBJEXT) Sock.$(OBJEXT) \
	makehouse.$(OBJEXT) puzzle.$(OBJEXT)
server_OBJECTS = $(am_server_OBJECTS)
server_DEPENDENCIES =
DEFAULT_INCLUDES = -I.
depcomp = $(SHELL) $(top_srcdir)/depcomp
am__depfiles_maybe = depfiles
am__mv = mv -f
COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
CCLD = $(CC)
LINK = $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(AM_LDFLAGS) $(LDFLAGS) -o $@
CXXCOMPILE = $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
	$(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
CXXLD = $(CXX)
CXXLINK = $(CXXLD) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_LDFLAGS) $(LDFLAGS) \
	-o $@
SOURCES = $(server_SOURCES)
DIST_SOURCES = $(server_SOURCES)
ETAGS = etags
CTAGS = ctags
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
distdir = $(PACKAGE)-$(VERSION)
top_distdir = $(distdir)
am__remove_distdir = \
  if test -d "$(distdir)"; then \
    find "$(distdir)" -type d ! -perm -200 -exec chmod u+w {} ';' \
      && rm -rf "$(distdir)" \
      || { sleep 5 && rm -rf "$(distdir)"; }; \
  else :; fi
DIST_ARCHIVES = $(distdir).tar.gz
GZIP_ENV = --best
distuninstallcheck_listfiles = find . -type f -print
am__distuninstallcheck_listfiles = $(distuninstallcheck_listfiles) \
  | sed 's|^\./|$(prefix)/|' | grep -v '$(infodir)/dir$$'
distcleancheck_listfiles = find . -type f -print
ACLOCAL = ${SHELL} /home/sxkj2/github/teachserver/missing --run aclocal-1.11
AMTAR = $${TAR-tar}
AUTOCONF = ${SHELL} /home/sxkj2/github/teachserver/missing --run autoconf
AUTOHEADER = ${SHELL} /home/sxkj2/github/teachserver/missing --run autoheader
AUTOMAKE = ${SHELL} /home/sxkj2/github/teachserver/missing --run automake-1.11
AWK = gawk
CC = gcc
CCDEPMODE = depmode=gcc3
CFLAGS = 
CPP = gcc -E
CPPFLAGS = 
CXX = g++
CXXDEPMODE = depmode=gcc3
CXXFLAGS = 
CYGPATH_W = echo
DEFS = -DHAVE_CONFIG_H
DEPDIR = .deps
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EGREP = /bin/grep -E
EXEEXT = 
GREP = /bin/grep
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
LDFLAGS = 
LIBOBJS = 
LIBS = 
LTLIBOBJS = 
MAKEINFO = ${SHELL} /home/sxkj2/github/teachserver/missing --run makeinfo
MKDIR_P = /bin/mkdir -p
OBJEXT = o
PACKAGE = main
PACKAGE_BUGREPORT = 
PACKAGE_NAME = server
PACKAGE_STRING = server 1.0
PACKAGE_TARNAME = server
PACKAGE_URL = 
PACKAGE_VERSION = 1.0
PATH_SEPARATOR = :
SET_MAKE = 
SHELL = /bin/bash
STRIP = 
VERSION = 1.0
abs_builddir = /home/sxkj2/github/teachserver
abs_srcdir = /home/sxkj2/github/teachserver
abs_top_builddir = /home/sxkj2/github/teachserver
abs_top_srcdir = /home/sxkj2/github/teachserver
ac_ct_CC = gcc
ac_ct_CXX = g++
am__include = include
am__leading_dot = .
am__quote = 
am__tar = $${TAR-tar} chof - "$$tardir"
am__untar = $${TAR-tar} xf -
bindir = ${exec_prefix}/bin
build_alias = 
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = ${prefix}
host_alias = 
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = ${SHELL} /home/sxkj2/github/teachserver/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
mkdir_p = /bin/mkdir -p
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /usr/local
program_transform_name = s,x,x,
psdir = ${docdir}
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
sysconfdir = ${prefix}/etc
target_alias = 
top_build_prefix = 
top_builddir = .
top_srcdir = .
AUTOMAKE_OPTIONS = gnu
INCLUDES = -I./handler -I./content
server_LDADD = -lglog -lpthread -llua5.2 -lev -ldl -lrt -lmysqlcppconn
#server_LDFLAGS = -g -Wall -Werror
#server_CFLAGS = -g -Wall -Werror
#server_CPPFLAGS= -g -Wall -Werror
server_SOURCES = ./main.cpp ./config.h ./Single.cpp ./QueueT.h \
	./Evloop.h ./SendTask.h ./ProcessManager.h ./Config.cpp \
	./Mutex.h ./handler/HandleMessage.cpp \
	./handler/HandleBuildHouse.cpp ./handler/HandleExercise.cpp \
	./handler/HandlePuzzle.cpp ./handler/HandleCartoon.cpp \
	./handler/HandleSprite.cpp ./handler/HandleMessage.h \
	./handler/HandleClassRoom.cpp ./ThreadPool.h ./twomapT.h \
	./database.h ./content/teacher.cpp ./content/courseitem.cpp \
	./content/roommanager.cpp ./content/course.cpp \
	./content/courseitem.h ./content/student.cpp ./content/room.h \
	./content/teacher.h ./content/student.h ./content/course.h \
	./content/game.cpp ./content/grade.h ./content/grade.cpp \
	./content/LoginCheck.cpp ./content/room.cpp \
	./content/roommanager.h ./content/LoginCheck.h \
	./content/game.h ./ThreadPool.cpp ./Sock.h ./database.cpp \
	./SQL.h ./protocol.h ./Buf.h ./PoolT.h ./Single.h ./task.h \
	./Evloop.cpp ./RecvTask.cpp ./AtomicT.h ./SendTask.cpp \
	./ProcessManager.cpp ./Config.h ./RecvTask.h ./Sock.c \
	./content/makehouse.cpp ./content/puzzle.cpp
all: config.h
	$(MAKE) $(AM_MAKEFLAGS) all-am

.SUFFIXES:
.SUFFIXES: .c .cpp .o .obj
am--refresh: Makefile
	@:
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      echo ' cd $(srcdir) && $(AUTOMAKE) --gnu'; \
	      $(am__cd) $(srcdir) && $(AUTOMAKE) --gnu \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --gnu Makefile'; \
	$(am__cd) $(top_srcdir) && \
	  $(AUTOMAKE) --gnu Makefile
.PRECIOUS: Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    echo ' $(SHELL) ./config.status'; \
	    $(SHELL) ./config.status;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck

$(top_srcdir)/configure:  $(am__configure_deps)
	$(am__cd) $(srcdir) && $(AUTOCONF)
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	$(am__cd) $(srcdir) && $(ACLOCAL) $(ACLOCAL_AMFLAGS)
$(am__aclocal_m4_deps):

config.h: stamp-h1
	@if test ! -f $@; then rm -f stamp-h1; else :; fi
	@if test ! -f $@; then $(MAKE) $(AM_MAKEFLAGS) stamp-h1; else :; fi

stamp-h1: $(srcdir)/config.h.in $(top_builddir)/config.status
	@rm -f stamp-h1
	cd $(top_builddir) && $(SHELL) ./config.status config.h
$(srcdir)/config.h.in:  $(am__configure_deps) 
	($(am__cd) $(top_srcdir) && $(AUTOHEADER))
	rm -f stamp-h1
	touch $@

distclean-hdr:
	-rm -f config.h stamp-h1
install-binPROGRAMS: $(bin_PROGRAMS)
	@$(NORMAL_INSTALL)
	test -z "$(bindir)" || $(MKDIR_P) "$(DESTDIR)$(bindir)"
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	for p in $$list; do echo "$$p $$p"; done | \
	sed 's/$(EXEEXT)$$//' | \
	while read p p1; do if test -f $$p; \
	  then echo "$$p"; echo "$$p"; else :; fi; \
	done | \
	sed -e 'p;s,.*/,,;n;h' -e 's|.*|.|' \
	    -e 'p;x;s,.*/,,;s/$(EXEEXT)$$//;$(transform);s/$$/$(EXEEXT)/' | \
	sed 'N;N;N;s,\n, ,g' | \
	$(AWK) 'BEGIN { files["."] = ""; dirs["."] = 1 } \
	  { d=$$3; if (dirs[d] != 1) { print "d", d; dirs[d] = 1 } \
	    if ($$2 == $$4) files[d] = files[d] " " $$1; \
	    else { print "f", $$3 "/" $$4, $$1; } } \
	  END { for (d in files) print "f", d, files[d] }' | \
	while read type dir files; do \
	    if test "$$dir" = .; then dir=; else dir=/$$dir; fi; \
	    test -z "$$files" || { \
	      echo " $(INSTALL_PROGRAM_ENV) $(INSTALL_PROGRAM) $$files '$(DESTDIR)$(bindir)$$dir'"; \
	      $(INSTALL_PROGRAM_ENV) $(INSTALL_PROGRAM) $$files "$(DESTDIR)$(bindir)$$dir" || exit $$?; \
	    } \
	; done

uninstall-binPROGRAMS:
	@$(NORMAL_UNINSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	files=`for p in $$list; do echo "$$p"; done | \
	  sed -e 'h;s,^.*/,,;s/$(EXEEXT)$$//;$(transform)' \
	      -e 's/$$/$(EXEEXT)/' `; \
	test -n "$$list" || exit 0; \
	echo " ( cd '$(DESTDIR)$(bindir)' && rm -f" $$files ")"; \
	cd "$(DESTDIR)$(bindir)" && rm -f $$files

clean-binPROGRAMS:
	-test -z "$(bin_PROGRAMS)" || rm -f $(bin_PROGRAMS)
server$(EXEEXT): $(server_OBJECTS) $(server_DEPENDENCIES) $(EXTRA_server_DEPENDENCIES) 
	@rm -f server$(EXEEXT)
	$(CXXLINK) $(server_OBJECTS) $(server_LDADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT)

distclean-compile:
	-rm -f *.tab.c

include ./$(DEPDIR)/Config.Po
include ./$(DEPDIR)/Evloop.Po
include ./$(DEPDIR)/HandleBuildHouse.Po
include ./$(DEPDIR)/HandleCartoon.Po
include ./$(DEPDIR)/HandleClassRoom.Po
include ./$(DEPDIR)/HandleExercise.Po
include ./$(DEPDIR)/HandleMessage.Po
include ./$(DEPDIR)/HandlePuzzle.Po
include ./$(DEPDIR)/HandleSprite.Po
include ./$(DEPDIR)/LoginCheck.Po
include ./$(DEPDIR)/ProcessManager.Po
include ./$(DEPDIR)/RecvTask.Po
include ./$(DEPDIR)/SendTask.Po
include ./$(DEPDIR)/Single.Po
include ./$(DEPDIR)/Sock.Po
include ./$(DEPDIR)/ThreadPool.Po
include ./$(DEPDIR)/course.Po
include ./$(DEPDIR)/courseitem.Po
include ./$(DEPDIR)/database.Po
include ./$(DEPDIR)/game.Po
include ./$(DEPDIR)/grade.Po
include ./$(DEPDIR)/main.Po
include ./$(DEPDIR)/makehouse.Po
include ./$(DEPDIR)/puzzle.Po
include ./$(DEPDIR)/room.Po
include ./$(DEPDIR)/roommanager.Po
include ./$(DEPDIR)/student.Po
include ./$(DEPDIR)/teacher.Po

.c.o:
	$(COMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ $<
	$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(COMPILE) -c $<

.c.obj:
	$(COMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ `$(CYGPATH_W) '$<'`
	$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(COMPILE) -c `$(CYGPATH_W) '$<'`

Sock.o: ./Sock.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT Sock.o -MD -MP -MF $(DEPDIR)/Sock.Tpo -c -o Sock.o `test -f './Sock.c' || echo '$(srcdir)/'`./Sock.c
	$(am__mv) $(DEPDIR)/Sock.Tpo $(DEPDIR)/Sock.Po
#	source='./Sock.c' object='Sock.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o Sock.o `test -f './Sock.c' || echo '$(srcdir)/'`./Sock.c

Sock.obj: ./Sock.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT Sock.obj -MD -MP -MF $(DEPDIR)/Sock.Tpo -c -o Sock.obj `if test -f './Sock.c'; then $(CYGPATH_W) './Sock.c'; else $(CYGPATH_W) '$(srcdir)/./Sock.c'; fi`
	$(am__mv) $(DEPDIR)/Sock.Tpo $(DEPDIR)/Sock.Po
#	source='./Sock.c' object='Sock.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o Sock.obj `if test -f './Sock.c'; then $(CYGPATH_W) './Sock.c'; else $(CYGPATH_W) '$(srcdir)/./Sock.c'; fi`

.cpp.o:
	$(CXXCOMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ $<
	$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXXCOMPILE) -c -o $@ $<

.cpp.obj:
	$(CXXCOMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ `$(CYGPATH_W) '$<'`
	$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXXCOMPILE) -c -o $@ `$(CYGPATH_W) '$<'`

main.o: ./main.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT main.o -MD -MP -MF $(DEPDIR)/main.Tpo -c -o main.o `test -f './main.cpp' || echo '$(srcdir)/'`./main.cpp
	$(am__mv) $(DEPDIR)/main.Tpo $(DEPDIR)/main.Po
#	source='./main.cpp' object='main.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o main.o `test -f './main.cpp' || echo '$(srcdir)/'`./main.cpp

main.obj: ./main.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT main.obj -MD -MP -MF $(DEPDIR)/main.Tpo -c -o main.obj `if test -f './main.cpp'; then $(CYGPATH_W) './main.cpp'; else $(CYGPATH_W) '$(srcdir)/./main.cpp'; fi`
	$(am__mv) $(DEPDIR)/main.Tpo $(DEPDIR)/main.Po
#	source='./main.cpp' object='main.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o main.obj `if test -f './main.cpp'; then $(CYGPATH_W) './main.cpp'; else $(CYGPATH_W) '$(srcdir)/./main.cpp'; fi`

Single.o: ./Single.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT Single.o -MD -MP -MF $(DEPDIR)/Single.Tpo -c -o Single.o `test -f './Single.cpp' || echo '$(srcdir)/'`./Single.cpp
	$(am__mv) $(DEPDIR)/Single.Tpo $(DEPDIR)/Single.Po
#	source='./Single.cpp' object='Single.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o Single.o `test -f './Single.cpp' || echo '$(srcdir)/'`./Single.cpp

Single.obj: ./Single.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT Single.obj -MD -MP -MF $(DEPDIR)/Single.Tpo -c -o Single.obj `if test -f './Single.cpp'; then $(CYGPATH_W) './Single.cpp'; else $(CYGPATH_W) '$(srcdir)/./Single.cpp'; fi`
	$(am__mv) $(DEPDIR)/Single.Tpo $(DEPDIR)/Single.Po
#	source='./Single.cpp' object='Single.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o Single.obj `if test -f './Single.cpp'; then $(CYGPATH_W) './Single.cpp'; else $(CYGPATH_W) '$(srcdir)/./Single.cpp'; fi`

Config.o: ./Config.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT Config.o -MD -MP -MF $(DEPDIR)/Config.Tpo -c -o Config.o `test -f './Config.cpp' || echo '$(srcdir)/'`./Config.cpp
	$(am__mv) $(DEPDIR)/Config.Tpo $(DEPDIR)/Config.Po
#	source='./Config.cpp' object='Config.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o Config.o `test -f './Config.cpp' || echo '$(srcdir)/'`./Config.cpp

Config.obj: ./Config.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT Config.obj -MD -MP -MF $(DEPDIR)/Config.Tpo -c -o Config.obj `if test -f './Config.cpp'; then $(CYGPATH_W) './Config.cpp'; else $(CYGPATH_W) '$(srcdir)/./Config.cpp'; fi`
	$(am__mv) $(DEPDIR)/Config.Tpo $(DEPDIR)/Config.Po
#	source='./Config.cpp' object='Config.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o Config.obj `if test -f './Config.cpp'; then $(CYGPATH_W) './Config.cpp'; else $(CYGPATH_W) '$(srcdir)/./Config.cpp'; fi`

HandleMessage.o: ./handler/HandleMessage.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT HandleMessage.o -MD -MP -MF $(DEPDIR)/HandleMessage.Tpo -c -o HandleMessage.o `test -f './handler/HandleMessage.cpp' || echo '$(srcdir)/'`./handler/HandleMessage.cpp
	$(am__mv) $(DEPDIR)/HandleMessage.Tpo $(DEPDIR)/HandleMessage.Po
#	source='./handler/HandleMessage.cpp' object='HandleMessage.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o HandleMessage.o `test -f './handler/HandleMessage.cpp' || echo '$(srcdir)/'`./handler/HandleMessage.cpp

HandleMessage.obj: ./handler/HandleMessage.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT HandleMessage.obj -MD -MP -MF $(DEPDIR)/HandleMessage.Tpo -c -o HandleMessage.obj `if test -f './handler/HandleMessage.cpp'; then $(CYGPATH_W) './handler/HandleMessage.cpp'; else $(CYGPATH_W) '$(srcdir)/./handler/HandleMessage.cpp'; fi`
	$(am__mv) $(DEPDIR)/HandleMessage.Tpo $(DEPDIR)/HandleMessage.Po
#	source='./handler/HandleMessage.cpp' object='HandleMessage.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o HandleMessage.obj `if test -f './handler/HandleMessage.cpp'; then $(CYGPATH_W) './handler/HandleMessage.cpp'; else $(CYGPATH_W) '$(srcdir)/./handler/HandleMessage.cpp'; fi`

HandleBuildHouse.o: ./handler/HandleBuildHouse.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT HandleBuildHouse.o -MD -MP -MF $(DEPDIR)/HandleBuildHouse.Tpo -c -o HandleBuildHouse.o `test -f './handler/HandleBuildHouse.cpp' || echo '$(srcdir)/'`./handler/HandleBuildHouse.cpp
	$(am__mv) $(DEPDIR)/HandleBuildHouse.Tpo $(DEPDIR)/HandleBuildHouse.Po
#	source='./handler/HandleBuildHouse.cpp' object='HandleBuildHouse.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o HandleBuildHouse.o `test -f './handler/HandleBuildHouse.cpp' || echo '$(srcdir)/'`./handler/HandleBuildHouse.cpp

HandleBuildHouse.obj: ./handler/HandleBuildHouse.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT HandleBuildHouse.obj -MD -MP -MF $(DEPDIR)/HandleBuildHouse.Tpo -c -o HandleBuildHouse.obj `if test -f './handler/HandleBuildHouse.cpp'; then $(CYGPATH_W) './handler/HandleBuildHouse.cpp'; else $(CYGPATH_W) '$(srcdir)/./handler/HandleBuildHouse.cpp'; fi`
	$(am__mv) $(DEPDIR)/HandleBuildHouse.Tpo $(DEPDIR)/HandleBuildHouse.Po
#	source='./handler/HandleBuildHouse.cpp' object='HandleBuildHouse.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o HandleBuildHouse.obj `if test -f './handler/HandleBuildHouse.cpp'; then $(CYGPATH_W) './handler/HandleBuildHouse.cpp'; else $(CYGPATH_W) '$(srcdir)/./handler/HandleBuildHouse.cpp'; fi`

HandleExercise.o: ./handler/HandleExercise.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT HandleExercise.o -MD -MP -MF $(DEPDIR)/HandleExercise.Tpo -c -o HandleExercise.o `test -f './handler/HandleExercise.cpp' || echo '$(srcdir)/'`./handler/HandleExercise.cpp
	$(am__mv) $(DEPDIR)/HandleExercise.Tpo $(DEPDIR)/HandleExercise.Po
#	source='./handler/HandleExercise.cpp' object='HandleExercise.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o HandleExercise.o `test -f './handler/HandleExercise.cpp' || echo '$(srcdir)/'`./handler/HandleExercise.cpp

HandleExercise.obj: ./handler/HandleExercise.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT HandleExercise.obj -MD -MP -MF $(DEPDIR)/HandleExercise.Tpo -c -o HandleExercise.obj `if test -f './handler/HandleExercise.cpp'; then $(CYGPATH_W) './handler/HandleExercise.cpp'; else $(CYGPATH_W) '$(srcdir)/./handler/HandleExercise.cpp'; fi`
	$(am__mv) $(DEPDIR)/HandleExercise.Tpo $(DEPDIR)/HandleExercise.Po
#	source='./handler/HandleExercise.cpp' object='HandleExercise.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o HandleExercise.obj `if test -f './handler/HandleExercise.cpp'; then $(CYGPATH_W) './handler/HandleExercise.cpp'; else $(CYGPATH_W) '$(srcdir)/./handler/HandleExercise.cpp'; fi`

HandlePuzzle.o: ./handler/HandlePuzzle.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT HandlePuzzle.o -MD -MP -MF $(DEPDIR)/HandlePuzzle.Tpo -c -o HandlePuzzle.o `test -f './handler/HandlePuzzle.cpp' || echo '$(srcdir)/'`./handler/HandlePuzzle.cpp
	$(am__mv) $(DEPDIR)/HandlePuzzle.Tpo $(DEPDIR)/HandlePuzzle.Po
#	source='./handler/HandlePuzzle.cpp' object='HandlePuzzle.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o HandlePuzzle.o `test -f './handler/HandlePuzzle.cpp' || echo '$(srcdir)/'`./handler/HandlePuzzle.cpp

HandlePuzzle.obj: ./handler/HandlePuzzle.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT HandlePuzzle.obj -MD -MP -MF $(DEPDIR)/HandlePuzzle.Tpo -c -o HandlePuzzle.obj `if test -f './handler/HandlePuzzle.cpp'; then $(CYGPATH_W) './handler/HandlePuzzle.cpp'; else $(CYGPATH_W) '$(srcdir)/./handler/HandlePuzzle.cpp'; fi`
	$(am__mv) $(DEPDIR)/HandlePuzzle.Tpo $(DEPDIR)/HandlePuzzle.Po
#	source='./handler/HandlePuzzle.cpp' object='HandlePuzzle.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o HandlePuzzle.obj `if test -f './handler/HandlePuzzle.cpp'; then $(CYGPATH_W) './handler/HandlePuzzle.cpp'; else $(CYGPATH_W) '$(srcdir)/./handler/HandlePuzzle.cpp'; fi`

HandleCartoon.o: ./handler/HandleCartoon.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT HandleCartoon.o -MD -MP -MF $(DEPDIR)/HandleCartoon.Tpo -c -o HandleCartoon.o `test -f './handler/HandleCartoon.cpp' || echo '$(srcdir)/'`./handler/HandleCartoon.cpp
	$(am__mv) $(DEPDIR)/HandleCartoon.Tpo $(DEPDIR)/HandleCartoon.Po
#	source='./handler/HandleCartoon.cpp' object='HandleCartoon.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o HandleCartoon.o `test -f './handler/HandleCartoon.cpp' || echo '$(srcdir)/'`./handler/HandleCartoon.cpp

HandleCartoon.obj: ./handler/HandleCartoon.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT HandleCartoon.obj -MD -MP -MF $(DEPDIR)/HandleCartoon.Tpo -c -o HandleCartoon.obj `if test -f './handler/HandleCartoon.cpp'; then $(CYGPATH_W) './handler/HandleCartoon.cpp'; else $(CYGPATH_W) '$(srcdir)/./handler/HandleCartoon.cpp'; fi`
	$(am__mv) $(DEPDIR)/HandleCartoon.Tpo $(DEPDIR)/HandleCartoon.Po
#	source='./handler/HandleCartoon.cpp' object='HandleCartoon.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o HandleCartoon.obj `if test -f './handler/HandleCartoon.cpp'; then $(CYGPATH_W) './handler/HandleCartoon.cpp'; else $(CYGPATH_W) '$(srcdir)/./handler/HandleCartoon.cpp'; fi`

HandleSprite.o: ./handler/HandleSprite.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT HandleSprite.o -MD -MP -MF $(DEPDIR)/HandleSprite.Tpo -c -o HandleSprite.o `test -f './handler/HandleSprite.cpp' || echo '$(srcdir)/'`./handler/HandleSprite.cpp
	$(am__mv) $(DEPDIR)/HandleSprite.Tpo $(DEPDIR)/HandleSprite.Po
#	source='./handler/HandleSprite.cpp' object='HandleSprite.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o HandleSprite.o `test -f './handler/HandleSprite.cpp' || echo '$(srcdir)/'`./handler/HandleSprite.cpp

HandleSprite.obj: ./handler/HandleSprite.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT HandleSprite.obj -MD -MP -MF $(DEPDIR)/HandleSprite.Tpo -c -o HandleSprite.obj `if test -f './handler/HandleSprite.cpp'; then $(CYGPATH_W) './handler/HandleSprite.cpp'; else $(CYGPATH_W) '$(srcdir)/./handler/HandleSprite.cpp'; fi`
	$(am__mv) $(DEPDIR)/HandleSprite.Tpo $(DEPDIR)/HandleSprite.Po
#	source='./handler/HandleSprite.cpp' object='HandleSprite.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o HandleSprite.obj `if test -f './handler/HandleSprite.cpp'; then $(CYGPATH_W) './handler/HandleSprite.cpp'; else $(CYGPATH_W) '$(srcdir)/./handler/HandleSprite.cpp'; fi`

HandleClassRoom.o: ./handler/HandleClassRoom.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT HandleClassRoom.o -MD -MP -MF $(DEPDIR)/HandleClassRoom.Tpo -c -o HandleClassRoom.o `test -f './handler/HandleClassRoom.cpp' || echo '$(srcdir)/'`./handler/HandleClassRoom.cpp
	$(am__mv) $(DEPDIR)/HandleClassRoom.Tpo $(DEPDIR)/HandleClassRoom.Po
#	source='./handler/HandleClassRoom.cpp' object='HandleClassRoom.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o HandleClassRoom.o `test -f './handler/HandleClassRoom.cpp' || echo '$(srcdir)/'`./handler/HandleClassRoom.cpp

HandleClassRoom.obj: ./handler/HandleClassRoom.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT HandleClassRoom.obj -MD -MP -MF $(DEPDIR)/HandleClassRoom.Tpo -c -o HandleClassRoom.obj `if test -f './handler/HandleClassRoom.cpp'; then $(CYGPATH_W) './handler/HandleClassRoom.cpp'; else $(CYGPATH_W) '$(srcdir)/./handler/HandleClassRoom.cpp'; fi`
	$(am__mv) $(DEPDIR)/HandleClassRoom.Tpo $(DEPDIR)/HandleClassRoom.Po
#	source='./handler/HandleClassRoom.cpp' object='HandleClassRoom.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o HandleClassRoom.obj `if test -f './handler/HandleClassRoom.cpp'; then $(CYGPATH_W) './handler/HandleClassRoom.cpp'; else $(CYGPATH_W) '$(srcdir)/./handler/HandleClassRoom.cpp'; fi`

teacher.o: ./content/teacher.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT teacher.o -MD -MP -MF $(DEPDIR)/teacher.Tpo -c -o teacher.o `test -f './content/teacher.cpp' || echo '$(srcdir)/'`./content/teacher.cpp
	$(am__mv) $(DEPDIR)/teacher.Tpo $(DEPDIR)/teacher.Po
#	source='./content/teacher.cpp' object='teacher.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o teacher.o `test -f './content/teacher.cpp' || echo '$(srcdir)/'`./content/teacher.cpp

teacher.obj: ./content/teacher.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT teacher.obj -MD -MP -MF $(DEPDIR)/teacher.Tpo -c -o teacher.obj `if test -f './content/teacher.cpp'; then $(CYGPATH_W) './content/teacher.cpp'; else $(CYGPATH_W) '$(srcdir)/./content/teacher.cpp'; fi`
	$(am__mv) $(DEPDIR)/teacher.Tpo $(DEPDIR)/teacher.Po
#	source='./content/teacher.cpp' object='teacher.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o teacher.obj `if test -f './content/teacher.cpp'; then $(CYGPATH_W) './content/teacher.cpp'; else $(CYGPATH_W) '$(srcdir)/./content/teacher.cpp'; fi`

courseitem.o: ./content/courseitem.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT courseitem.o -MD -MP -MF $(DEPDIR)/courseitem.Tpo -c -o courseitem.o `test -f './content/courseitem.cpp' || echo '$(srcdir)/'`./content/courseitem.cpp
	$(am__mv) $(DEPDIR)/courseitem.Tpo $(DEPDIR)/courseitem.Po
#	source='./content/courseitem.cpp' object='courseitem.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o courseitem.o `test -f './content/courseitem.cpp' || echo '$(srcdir)/'`./content/courseitem.cpp

courseitem.obj: ./content/courseitem.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT courseitem.obj -MD -MP -MF $(DEPDIR)/courseitem.Tpo -c -o courseitem.obj `if test -f './content/courseitem.cpp'; then $(CYGPATH_W) './content/courseitem.cpp'; else $(CYGPATH_W) '$(srcdir)/./content/courseitem.cpp'; fi`
	$(am__mv) $(DEPDIR)/courseitem.Tpo $(DEPDIR)/courseitem.Po
#	source='./content/courseitem.cpp' object='courseitem.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o courseitem.obj `if test -f './content/courseitem.cpp'; then $(CYGPATH_W) './content/courseitem.cpp'; else $(CYGPATH_W) '$(srcdir)/./content/courseitem.cpp'; fi`

roommanager.o: ./content/roommanager.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT roommanager.o -MD -MP -MF $(DEPDIR)/roommanager.Tpo -c -o roommanager.o `test -f './content/roommanager.cpp' || echo '$(srcdir)/'`./content/roommanager.cpp
	$(am__mv) $(DEPDIR)/roommanager.Tpo $(DEPDIR)/roommanager.Po
#	source='./content/roommanager.cpp' object='roommanager.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o roommanager.o `test -f './content/roommanager.cpp' || echo '$(srcdir)/'`./content/roommanager.cpp

roommanager.obj: ./content/roommanager.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT roommanager.obj -MD -MP -MF $(DEPDIR)/roommanager.Tpo -c -o roommanager.obj `if test -f './content/roommanager.cpp'; then $(CYGPATH_W) './content/roommanager.cpp'; else $(CYGPATH_W) '$(srcdir)/./content/roommanager.cpp'; fi`
	$(am__mv) $(DEPDIR)/roommanager.Tpo $(DEPDIR)/roommanager.Po
#	source='./content/roommanager.cpp' object='roommanager.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o roommanager.obj `if test -f './content/roommanager.cpp'; then $(CYGPATH_W) './content/roommanager.cpp'; else $(CYGPATH_W) '$(srcdir)/./content/roommanager.cpp'; fi`

course.o: ./content/course.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT course.o -MD -MP -MF $(DEPDIR)/course.Tpo -c -o course.o `test -f './content/course.cpp' || echo '$(srcdir)/'`./content/course.cpp
	$(am__mv) $(DEPDIR)/course.Tpo $(DEPDIR)/course.Po
#	source='./content/course.cpp' object='course.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o course.o `test -f './content/course.cpp' || echo '$(srcdir)/'`./content/course.cpp

course.obj: ./content/course.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT course.obj -MD -MP -MF $(DEPDIR)/course.Tpo -c -o course.obj `if test -f './content/course.cpp'; then $(CYGPATH_W) './content/course.cpp'; else $(CYGPATH_W) '$(srcdir)/./content/course.cpp'; fi`
	$(am__mv) $(DEPDIR)/course.Tpo $(DEPDIR)/course.Po
#	source='./content/course.cpp' object='course.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o course.obj `if test -f './content/course.cpp'; then $(CYGPATH_W) './content/course.cpp'; else $(CYGPATH_W) '$(srcdir)/./content/course.cpp'; fi`

student.o: ./content/student.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT student.o -MD -MP -MF $(DEPDIR)/student.Tpo -c -o student.o `test -f './content/student.cpp' || echo '$(srcdir)/'`./content/student.cpp
	$(am__mv) $(DEPDIR)/student.Tpo $(DEPDIR)/student.Po
#	source='./content/student.cpp' object='student.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o student.o `test -f './content/student.cpp' || echo '$(srcdir)/'`./content/student.cpp

student.obj: ./content/student.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT student.obj -MD -MP -MF $(DEPDIR)/student.Tpo -c -o student.obj `if test -f './content/student.cpp'; then $(CYGPATH_W) './content/student.cpp'; else $(CYGPATH_W) '$(srcdir)/./content/student.cpp'; fi`
	$(am__mv) $(DEPDIR)/student.Tpo $(DEPDIR)/student.Po
#	source='./content/student.cpp' object='student.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o student.obj `if test -f './content/student.cpp'; then $(CYGPATH_W) './content/student.cpp'; else $(CYGPATH_W) '$(srcdir)/./content/student.cpp'; fi`

game.o: ./content/game.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT game.o -MD -MP -MF $(DEPDIR)/game.Tpo -c -o game.o `test -f './content/game.cpp' || echo '$(srcdir)/'`./content/game.cpp
	$(am__mv) $(DEPDIR)/game.Tpo $(DEPDIR)/game.Po
#	source='./content/game.cpp' object='game.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o game.o `test -f './content/game.cpp' || echo '$(srcdir)/'`./content/game.cpp

game.obj: ./content/game.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT game.obj -MD -MP -MF $(DEPDIR)/game.Tpo -c -o game.obj `if test -f './content/game.cpp'; then $(CYGPATH_W) './content/game.cpp'; else $(CYGPATH_W) '$(srcdir)/./content/game.cpp'; fi`
	$(am__mv) $(DEPDIR)/game.Tpo $(DEPDIR)/game.Po
#	source='./content/game.cpp' object='game.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o game.obj `if test -f './content/game.cpp'; then $(CYGPATH_W) './content/game.cpp'; else $(CYGPATH_W) '$(srcdir)/./content/game.cpp'; fi`

grade.o: ./content/grade.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT grade.o -MD -MP -MF $(DEPDIR)/grade.Tpo -c -o grade.o `test -f './content/grade.cpp' || echo '$(srcdir)/'`./content/grade.cpp
	$(am__mv) $(DEPDIR)/grade.Tpo $(DEPDIR)/grade.Po
#	source='./content/grade.cpp' object='grade.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o grade.o `test -f './content/grade.cpp' || echo '$(srcdir)/'`./content/grade.cpp

grade.obj: ./content/grade.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT grade.obj -MD -MP -MF $(DEPDIR)/grade.Tpo -c -o grade.obj `if test -f './content/grade.cpp'; then $(CYGPATH_W) './content/grade.cpp'; else $(CYGPATH_W) '$(srcdir)/./content/grade.cpp'; fi`
	$(am__mv) $(DEPDIR)/grade.Tpo $(DEPDIR)/grade.Po
#	source='./content/grade.cpp' object='grade.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o grade.obj `if test -f './content/grade.cpp'; then $(CYGPATH_W) './content/grade.cpp'; else $(CYGPATH_W) '$(srcdir)/./content/grade.cpp'; fi`

LoginCheck.o: ./content/LoginCheck.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT LoginCheck.o -MD -MP -MF $(DEPDIR)/LoginCheck.Tpo -c -o LoginCheck.o `test -f './content/LoginCheck.cpp' || echo '$(srcdir)/'`./content/LoginCheck.cpp
	$(am__mv) $(DEPDIR)/LoginCheck.Tpo $(DEPDIR)/LoginCheck.Po
#	source='./content/LoginCheck.cpp' object='LoginCheck.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o LoginCheck.o `test -f './content/LoginCheck.cpp' || echo '$(srcdir)/'`./content/LoginCheck.cpp

LoginCheck.obj: ./content/LoginCheck.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT LoginCheck.obj -MD -MP -MF $(DEPDIR)/LoginCheck.Tpo -c -o LoginCheck.obj `if test -f './content/LoginCheck.cpp'; then $(CYGPATH_W) './content/LoginCheck.cpp'; else $(CYGPATH_W) '$(srcdir)/./content/LoginCheck.cpp'; fi`
	$(am__mv) $(DEPDIR)/LoginCheck.Tpo $(DEPDIR)/LoginCheck.Po
#	source='./content/LoginCheck.cpp' object='LoginCheck.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o LoginCheck.obj `if test -f './content/LoginCheck.cpp'; then $(CYGPATH_W) './content/LoginCheck.cpp'; else $(CYGPATH_W) '$(srcdir)/./content/LoginCheck.cpp'; fi`

room.o: ./content/room.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT room.o -MD -MP -MF $(DEPDIR)/room.Tpo -c -o room.o `test -f './content/room.cpp' || echo '$(srcdir)/'`./content/room.cpp
	$(am__mv) $(DEPDIR)/room.Tpo $(DEPDIR)/room.Po
#	source='./content/room.cpp' object='room.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o room.o `test -f './content/room.cpp' || echo '$(srcdir)/'`./content/room.cpp

room.obj: ./content/room.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT room.obj -MD -MP -MF $(DEPDIR)/room.Tpo -c -o room.obj `if test -f './content/room.cpp'; then $(CYGPATH_W) './content/room.cpp'; else $(CYGPATH_W) '$(srcdir)/./content/room.cpp'; fi`
	$(am__mv) $(DEPDIR)/room.Tpo $(DEPDIR)/room.Po
#	source='./content/room.cpp' object='room.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o room.obj `if test -f './content/room.cpp'; then $(CYGPATH_W) './content/room.cpp'; else $(CYGPATH_W) '$(srcdir)/./content/room.cpp'; fi`

ThreadPool.o: ./ThreadPool.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT ThreadPool.o -MD -MP -MF $(DEPDIR)/ThreadPool.Tpo -c -o ThreadPool.o `test -f './ThreadPool.cpp' || echo '$(srcdir)/'`./ThreadPool.cpp
	$(am__mv) $(DEPDIR)/ThreadPool.Tpo $(DEPDIR)/ThreadPool.Po
#	source='./ThreadPool.cpp' object='ThreadPool.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o ThreadPool.o `test -f './ThreadPool.cpp' || echo '$(srcdir)/'`./ThreadPool.cpp

ThreadPool.obj: ./ThreadPool.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT ThreadPool.obj -MD -MP -MF $(DEPDIR)/ThreadPool.Tpo -c -o ThreadPool.obj `if test -f './ThreadPool.cpp'; then $(CYGPATH_W) './ThreadPool.cpp'; else $(CYGPATH_W) '$(srcdir)/./ThreadPool.cpp'; fi`
	$(am__mv) $(DEPDIR)/ThreadPool.Tpo $(DEPDIR)/ThreadPool.Po
#	source='./ThreadPool.cpp' object='ThreadPool.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o ThreadPool.obj `if test -f './ThreadPool.cpp'; then $(CYGPATH_W) './ThreadPool.cpp'; else $(CYGPATH_W) '$(srcdir)/./ThreadPool.cpp'; fi`

database.o: ./database.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT database.o -MD -MP -MF $(DEPDIR)/database.Tpo -c -o database.o `test -f './database.cpp' || echo '$(srcdir)/'`./database.cpp
	$(am__mv) $(DEPDIR)/database.Tpo $(DEPDIR)/database.Po
#	source='./database.cpp' object='database.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o database.o `test -f './database.cpp' || echo '$(srcdir)/'`./database.cpp

database.obj: ./database.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT database.obj -MD -MP -MF $(DEPDIR)/database.Tpo -c -o database.obj `if test -f './database.cpp'; then $(CYGPATH_W) './database.cpp'; else $(CYGPATH_W) '$(srcdir)/./database.cpp'; fi`
	$(am__mv) $(DEPDIR)/database.Tpo $(DEPDIR)/database.Po
#	source='./database.cpp' object='database.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o database.obj `if test -f './database.cpp'; then $(CYGPATH_W) './database.cpp'; else $(CYGPATH_W) '$(srcdir)/./database.cpp'; fi`

Evloop.o: ./Evloop.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT Evloop.o -MD -MP -MF $(DEPDIR)/Evloop.Tpo -c -o Evloop.o `test -f './Evloop.cpp' || echo '$(srcdir)/'`./Evloop.cpp
	$(am__mv) $(DEPDIR)/Evloop.Tpo $(DEPDIR)/Evloop.Po
#	source='./Evloop.cpp' object='Evloop.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o Evloop.o `test -f './Evloop.cpp' || echo '$(srcdir)/'`./Evloop.cpp

Evloop.obj: ./Evloop.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT Evloop.obj -MD -MP -MF $(DEPDIR)/Evloop.Tpo -c -o Evloop.obj `if test -f './Evloop.cpp'; then $(CYGPATH_W) './Evloop.cpp'; else $(CYGPATH_W) '$(srcdir)/./Evloop.cpp'; fi`
	$(am__mv) $(DEPDIR)/Evloop.Tpo $(DEPDIR)/Evloop.Po
#	source='./Evloop.cpp' object='Evloop.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o Evloop.obj `if test -f './Evloop.cpp'; then $(CYGPATH_W) './Evloop.cpp'; else $(CYGPATH_W) '$(srcdir)/./Evloop.cpp'; fi`

RecvTask.o: ./RecvTask.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT RecvTask.o -MD -MP -MF $(DEPDIR)/RecvTask.Tpo -c -o RecvTask.o `test -f './RecvTask.cpp' || echo '$(srcdir)/'`./RecvTask.cpp
	$(am__mv) $(DEPDIR)/RecvTask.Tpo $(DEPDIR)/RecvTask.Po
#	source='./RecvTask.cpp' object='RecvTask.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o RecvTask.o `test -f './RecvTask.cpp' || echo '$(srcdir)/'`./RecvTask.cpp

RecvTask.obj: ./RecvTask.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT RecvTask.obj -MD -MP -MF $(DEPDIR)/RecvTask.Tpo -c -o RecvTask.obj `if test -f './RecvTask.cpp'; then $(CYGPATH_W) './RecvTask.cpp'; else $(CYGPATH_W) '$(srcdir)/./RecvTask.cpp'; fi`
	$(am__mv) $(DEPDIR)/RecvTask.Tpo $(DEPDIR)/RecvTask.Po
#	source='./RecvTask.cpp' object='RecvTask.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o RecvTask.obj `if test -f './RecvTask.cpp'; then $(CYGPATH_W) './RecvTask.cpp'; else $(CYGPATH_W) '$(srcdir)/./RecvTask.cpp'; fi`

SendTask.o: ./SendTask.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT SendTask.o -MD -MP -MF $(DEPDIR)/SendTask.Tpo -c -o SendTask.o `test -f './SendTask.cpp' || echo '$(srcdir)/'`./SendTask.cpp
	$(am__mv) $(DEPDIR)/SendTask.Tpo $(DEPDIR)/SendTask.Po
#	source='./SendTask.cpp' object='SendTask.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o SendTask.o `test -f './SendTask.cpp' || echo '$(srcdir)/'`./SendTask.cpp

SendTask.obj: ./SendTask.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT SendTask.obj -MD -MP -MF $(DEPDIR)/SendTask.Tpo -c -o SendTask.obj `if test -f './SendTask.cpp'; then $(CYGPATH_W) './SendTask.cpp'; else $(CYGPATH_W) '$(srcdir)/./SendTask.cpp'; fi`
	$(am__mv) $(DEPDIR)/SendTask.Tpo $(DEPDIR)/SendTask.Po
#	source='./SendTask.cpp' object='SendTask.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o SendTask.obj `if test -f './SendTask.cpp'; then $(CYGPATH_W) './SendTask.cpp'; else $(CYGPATH_W) '$(srcdir)/./SendTask.cpp'; fi`

ProcessManager.o: ./ProcessManager.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT ProcessManager.o -MD -MP -MF $(DEPDIR)/ProcessManager.Tpo -c -o ProcessManager.o `test -f './ProcessManager.cpp' || echo '$(srcdir)/'`./ProcessManager.cpp
	$(am__mv) $(DEPDIR)/ProcessManager.Tpo $(DEPDIR)/ProcessManager.Po
#	source='./ProcessManager.cpp' object='ProcessManager.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o ProcessManager.o `test -f './ProcessManager.cpp' || echo '$(srcdir)/'`./ProcessManager.cpp

ProcessManager.obj: ./ProcessManager.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT ProcessManager.obj -MD -MP -MF $(DEPDIR)/ProcessManager.Tpo -c -o ProcessManager.obj `if test -f './ProcessManager.cpp'; then $(CYGPATH_W) './ProcessManager.cpp'; else $(CYGPATH_W) '$(srcdir)/./ProcessManager.cpp'; fi`
	$(am__mv) $(DEPDIR)/ProcessManager.Tpo $(DEPDIR)/ProcessManager.Po
#	source='./ProcessManager.cpp' object='ProcessManager.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o ProcessManager.obj `if test -f './ProcessManager.cpp'; then $(CYGPATH_W) './ProcessManager.cpp'; else $(CYGPATH_W) '$(srcdir)/./ProcessManager.cpp'; fi`

makehouse.o: ./content/makehouse.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT makehouse.o -MD -MP -MF $(DEPDIR)/makehouse.Tpo -c -o makehouse.o `test -f './content/makehouse.cpp' || echo '$(srcdir)/'`./content/makehouse.cpp
	$(am__mv) $(DEPDIR)/makehouse.Tpo $(DEPDIR)/makehouse.Po
#	source='./content/makehouse.cpp' object='makehouse.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o makehouse.o `test -f './content/makehouse.cpp' || echo '$(srcdir)/'`./content/makehouse.cpp

makehouse.obj: ./content/makehouse.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT makehouse.obj -MD -MP -MF $(DEPDIR)/makehouse.Tpo -c -o makehouse.obj `if test -f './content/makehouse.cpp'; then $(CYGPATH_W) './content/makehouse.cpp'; else $(CYGPATH_W) '$(srcdir)/./content/makehouse.cpp'; fi`
	$(am__mv) $(DEPDIR)/makehouse.Tpo $(DEPDIR)/makehouse.Po
#	source='./content/makehouse.cpp' object='makehouse.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o makehouse.obj `if test -f './content/makehouse.cpp'; then $(CYGPATH_W) './content/makehouse.cpp'; else $(CYGPATH_W) '$(srcdir)/./content/makehouse.cpp'; fi`

puzzle.o: ./content/puzzle.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT puzzle.o -MD -MP -MF $(DEPDIR)/puzzle.Tpo -c -o puzzle.o `test -f './content/puzzle.cpp' || echo '$(srcdir)/'`./content/puzzle.cpp
	$(am__mv) $(DEPDIR)/puzzle.Tpo $(DEPDIR)/puzzle.Po
#	source='./content/puzzle.cpp' object='puzzle.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o puzzle.o `test -f './content/puzzle.cpp' || echo '$(srcdir)/'`./content/puzzle.cpp

puzzle.obj: ./content/puzzle.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT puzzle.obj -MD -MP -MF $(DEPDIR)/puzzle.Tpo -c -o puzzle.obj `if test -f './content/puzzle.cpp'; then $(CYGPATH_W) './content/puzzle.cpp'; else $(CYGPATH_W) '$(srcdir)/./content/puzzle.cpp'; fi`
	$(am__mv) $(DEPDIR)/puzzle.Tpo $(DEPDIR)/puzzle.Po
#	source='./content/puzzle.cpp' object='puzzle.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o puzzle.obj `if test -f './content/puzzle.cpp'; then $(CYGPATH_W) './content/puzzle.cpp'; else $(CYGPATH_W) '$(srcdir)/./content/puzzle.cpp'; fi`

ID: $(HEADERS) $(SOURCES) $(LISP) $(TAGS_FILES)
	list='$(SOURCES) $(HEADERS) $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	mkid -fID $$unique
tags: TAGS

TAGS:  $(HEADERS) $(SOURCES) config.h.in $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	set x; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS) config.h.in $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	shift; \
	if test -z "$(ETAGS_ARGS)$$*$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  if test $$# -gt 0; then \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      "$$@" $$unique; \
	  else \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      $$unique; \
	  fi; \
	fi
ctags: CTAGS
CTAGS:  $(HEADERS) $(SOURCES) config.h.in $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	list='$(SOURCES) $(HEADERS) config.h.in $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	test -z "$(CTAGS_ARGS)$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && $(am__cd) $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) "$$here"

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags

distdir: $(DISTFILES)
	$(am__remove_distdir)
	test -d "$(distdir)" || mkdir "$(distdir)"
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d "$(distdir)/$$file"; then \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -fpR $(srcdir)/$$file "$(distdir)$$dir" || exit 1; \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    cp -fpR $$d/$$file "$(distdir)$$dir" || exit 1; \
	  else \
	    test -f "$(distdir)/$$file" \
	    || cp -p $$d/$$file "$(distdir)/$$file" \
	    || exit 1; \
	  fi; \
	done
	-test -n "$(am__skip_mode_fix)" \
	|| find "$(distdir)" -type d ! -perm -755 \
		-exec chmod u+rwx,go+rx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec $(install_sh) -c -m a+r {} {} \; \
	|| chmod -R a+r "$(distdir)"
dist-gzip: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__remove_distdir)

dist-bzip2: distdir
	tardir=$(distdir) && $(am__tar) | BZIP2=$${BZIP2--9} bzip2 -c >$(distdir).tar.bz2
	$(am__remove_distdir)

dist-lzip: distdir
	tardir=$(distdir) && $(am__tar) | lzip -c $${LZIP_OPT--9} >$(distdir).tar.lz
	$(am__remove_distdir)

dist-lzma: distdir
	tardir=$(distdir) && $(am__tar) | lzma -9 -c >$(distdir).tar.lzma
	$(am__remove_distdir)

dist-xz: distdir
	tardir=$(distdir) && $(am__tar) | XZ_OPT=$${XZ_OPT--e} xz -c >$(distdir).tar.xz
	$(am__remove_distdir)

dist-tarZ: distdir
	tardir=$(distdir) && $(am__tar) | compress -c >$(distdir).tar.Z
	$(am__remove_distdir)

dist-shar: distdir
	shar $(distdir) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).shar.gz
	$(am__remove_distdir)

dist-zip: distdir
	-rm -f $(distdir).zip
	zip -rq $(distdir).zip $(distdir)
	$(am__remove_distdir)

dist dist-all: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__remove_distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	case '$(DIST_ARCHIVES)' in \
	*.tar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).tar.gz | $(am__untar) ;;\
	*.tar.bz2*) \
	  bzip2 -dc $(distdir).tar.bz2 | $(am__untar) ;;\
	*.tar.lzma*) \
	  lzma -dc $(distdir).tar.lzma | $(am__untar) ;;\
	*.tar.lz*) \
	  lzip -dc $(distdir).tar.lz | $(am__untar) ;;\
	*.tar.xz*) \
	  xz -dc $(distdir).tar.xz | $(am__untar) ;;\
	*.tar.Z*) \
	  uncompress -c $(distdir).tar.Z | $(am__untar) ;;\
	*.shar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).shar.gz | unshar ;;\
	*.zip*) \
	  unzip $(distdir).zip ;;\
	esac
	chmod -R a-w $(distdir); chmod a+w $(distdir)
	mkdir $(distdir)/_build
	mkdir $(distdir)/_inst
	chmod a-w $(distdir)
	test -d $(distdir)/_build || exit 0; \
	dc_install_base=`$(am__cd) $(distdir)/_inst && pwd | sed -e 's,^[^:\\/]:[\\/],/,'` \
	  && dc_destdir="$${TMPDIR-/tmp}/am-dc-$$$$/" \
	  && am__cwd=`pwd` \
	  && $(am__cd) $(distdir)/_build \
	  && ../configure --srcdir=.. --prefix="$$dc_install_base" \
	    $(AM_DISTCHECK_CONFIGURE_FLAGS) \
	    $(DISTCHECK_CONFIGURE_FLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) dvi \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) uninstall \
	  && $(MAKE) $(AM_MAKEFLAGS) distuninstallcheck_dir="$$dc_install_base" \
	        distuninstallcheck \
	  && chmod -R a-w "$$dc_install_base" \
	  && ({ \
	       (cd ../.. && umask 077 && mkdir "$$dc_destdir") \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" install \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" uninstall \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" \
	            distuninstallcheck_dir="$$dc_destdir" distuninstallcheck; \
	      } || { rm -rf "$$dc_destdir"; exit 1; }) \
	  && rm -rf "$$dc_destdir" \
	  && $(MAKE) $(AM_MAKEFLAGS) dist \
	  && rm -rf $(DIST_ARCHIVES) \
	  && $(MAKE) $(AM_MAKEFLAGS) distcleancheck \
	  && cd "$$am__cwd" \
	  || exit 1
	$(am__remove_distdir)
	@(echo "$(distdir) archives ready for distribution: "; \
	  list='$(DIST_ARCHIVES)'; for i in $$list; do echo $$i; done) | \
	  sed -e 1h -e 1s/./=/g -e 1p -e 1x -e '$$p' -e '$$x'
distuninstallcheck:
	@test -n '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: trying to run $@ with an empty' \
	       '$$(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	$(am__cd) '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: cannot chdir into $(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	test `$(am__distuninstallcheck_listfiles) | wc -l` -eq 0 \
	   || { echo "ERROR: files left after uninstall:" ; \
	        if test -n "$(DESTDIR)"; then \
	          echo "  (check DESTDIR support)"; \
	        fi ; \
	        $(distuninstallcheck_listfiles) ; \
	        exit 1; } >&2
distcleancheck: distclean
	@if test '$(srcdir)' = . ; then \
	  echo "ERROR: distcleancheck can only run from a VPATH build" ; \
	  exit 1 ; \
	fi
	@test `$(distcleancheck_listfiles) | wc -l` -eq 0 \
	  || { echo "ERROR: files left in build directory after distclean:" ; \
	       $(distcleancheck_listfiles) ; \
	       exit 1; } >&2
check-am: all-am
check: check-am
all-am: Makefile $(PROGRAMS) config.h
installdirs:
	for dir in "$(DESTDIR)$(bindir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	if test -z '$(STRIP)'; then \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	      install; \
	else \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	    "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'" install; \
	fi
mostlyclean-generic:

clean-generic:

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
	-test . = "$(srcdir)" || test -z "$(CONFIG_CLEAN_VPATH_FILES)" || rm -f $(CONFIG_CLEAN_VPATH_FILES)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-am

clean-am: clean-binPROGRAMS clean-generic mostlyclean-am

distclean: distclean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-hdr distclean-tags

dvi: dvi-am

dvi-am:

html: html-am

html-am:

info: info-am

info-am:

install-data-am:

install-dvi: install-dvi-am

install-dvi-am:

install-exec-am: install-binPROGRAMS

install-html: install-html-am

install-html-am:

install-info: install-info-am

install-info-am:

install-man:

install-pdf: install-pdf-am

install-pdf-am:

install-ps: install-ps-am

install-ps-am:

installcheck-am:

maintainer-clean: maintainer-clean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf $(top_srcdir)/autom4te.cache
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic

pdf: pdf-am

pdf-am:

ps: ps-am

ps-am:

uninstall-am: uninstall-binPROGRAMS

.MAKE: all install-am install-strip

.PHONY: CTAGS GTAGS all all-am am--refresh check check-am clean \
	clean-binPROGRAMS clean-generic ctags dist dist-all dist-bzip2 \
	dist-gzip dist-lzip dist-lzma dist-shar dist-tarZ dist-xz \
	dist-zip distcheck distclean distclean-compile \
	distclean-generic distclean-hdr distclean-tags distcleancheck \
	distdir distuninstallcheck dvi dvi-am html html-am info \
	info-am install install-am install-binPROGRAMS install-data \
	install-data-am install-dvi install-dvi-am install-exec \
	install-exec-am install-html install-html-am install-info \
	install-info-am install-man install-pdf install-pdf-am \
	install-ps install-ps-am install-strip installcheck \
	installcheck-am installdirs maintainer-clean \
	maintainer-clean-generic mostlyclean mostlyclean-compile \
	mostlyclean-generic pdf pdf-am ps ps-am tags uninstall \
	uninstall-am uninstall-binPROGRAMS


# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
