# Makefile.in generated by automake 1.11.3 from Makefile.am.
# Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002,
# 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011 Free Software
# Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.




pkgdatadir = $(datadir)/main
pkgincludedir = $(includedir)/main
pkglibdir = $(libdir)/main
pkglibexecdir = $(libexecdir)/main
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
bin_PROGRAMS = server$(EXEEXT)
subdir = .
DIST_COMMON = README $(am__configure_deps) $(srcdir)/Makefile.am \
	$(srcdir)/Makefile.in $(srcdir)/config.h.in \
	$(top_srcdir)/configure AUTHORS COPYING ChangeLog INSTALL NEWS \
	depcomp install-sh missing
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/configure.in
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
 configure.lineno config.status.lineno
mkinstalldirs = $(install_sh) -d
CONFIG_HEADER = config.h
CONFIG_CLEAN_FILES =
CONFIG_CLEAN_VPATH_FILES =
am__installdirs = "$(DESTDIR)$(bindir)"
PROGRAMS = $(bin_PROGRAMS)
am_server_OBJECTS = server-main.$(OBJEXT) server-Single.$(OBJEXT) \
	server-Config.$(OBJEXT) server-HandleMessage.$(OBJEXT) \
	server-HandleBuildHouse.$(OBJEXT) \
	server-HandleExercise.$(OBJEXT) server-HandlePuzzle.$(OBJEXT) \
	server-HandleCartoon.$(OBJEXT) server-HandleSprite.$(OBJEXT) \
	server-HandleClassRoom.$(OBJEXT) server-teacher.$(OBJEXT) \
	server-courseitem.$(OBJEXT) server-roommanager.$(OBJEXT) \
	server-course.$(OBJEXT) server-student.$(OBJEXT) \
	server-game.$(OBJEXT) server-grade.$(OBJEXT) \
	server-LoginCheck.$(OBJEXT) server-room.$(OBJEXT) \
	server-ThreadPool.$(OBJEXT) server-database.$(OBJEXT) \
	server-Evloop.$(OBJEXT) server-RecvTask.$(OBJEXT) \
	server-SendTask.$(OBJEXT) server-ProcessManager.$(OBJEXT) \
	server-Sock.$(OBJEXT)
server_OBJECTS = $(am_server_OBJECTS)
server_DEPENDENCIES =
server_LINK = $(CXXLD) $(AM_CXXFLAGS) $(CXXFLAGS) $(server_LDFLAGS) \
	$(LDFLAGS) -o $@
DEFAULT_INCLUDES = -I.
depcomp = $(SHELL) $(top_srcdir)/depcomp
am__depfiles_maybe = depfiles
am__mv = mv -f
COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
CCLD = $(CC)
LINK = $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(AM_LDFLAGS) $(LDFLAGS) -o $@
CXXCOMPILE = $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
	$(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
CXXLD = $(CXX)
CXXLINK = $(CXXLD) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_LDFLAGS) $(LDFLAGS) \
	-o $@
SOURCES = $(server_SOURCES)
DIST_SOURCES = $(server_SOURCES)
ETAGS = etags
CTAGS = ctags
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
distdir = $(PACKAGE)-$(VERSION)
top_distdir = $(distdir)
am__remove_distdir = \
  if test -d "$(distdir)"; then \
    find "$(distdir)" -type d ! -perm -200 -exec chmod u+w {} ';' \
      && rm -rf "$(distdir)" \
      || { sleep 5 && rm -rf "$(distdir)"; }; \
  else :; fi
DIST_ARCHIVES = $(distdir).tar.gz
GZIP_ENV = --best
distuninstallcheck_listfiles = find . -type f -print
am__distuninstallcheck_listfiles = $(distuninstallcheck_listfiles) \
  | sed 's|^\./|$(prefix)/|' | grep -v '$(infodir)/dir$$'
distcleancheck_listfiles = find . -type f -print
ACLOCAL = ${SHELL} /home/fu9ang/teachserver/missing --run aclocal-1.11
AMTAR = $${TAR-tar}
AUTOCONF = ${SHELL} /home/fu9ang/teachserver/missing --run autoconf
AUTOHEADER = ${SHELL} /home/fu9ang/teachserver/missing --run autoheader
AUTOMAKE = ${SHELL} /home/fu9ang/teachserver/missing --run automake-1.11
AWK = mawk
CC = gcc
CCDEPMODE = depmode=gcc3
CFLAGS = -g -O2
CPP = gcc -E
CPPFLAGS = 
CXX = g++
CXXDEPMODE = depmode=gcc3
CXXFLAGS = -g -O2
CYGPATH_W = echo
DEFS = -DHAVE_CONFIG_H
DEPDIR = .deps
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EGREP = /bin/grep -E
EXEEXT = 
GREP = /bin/grep
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
LDFLAGS = 
LIBOBJS = 
LIBS = 
LTLIBOBJS = 
MAKEINFO = ${SHELL} /home/fu9ang/teachserver/missing --run makeinfo
MKDIR_P = /bin/mkdir -p
OBJEXT = o
PACKAGE = main
PACKAGE_BUGREPORT = 
PACKAGE_NAME = server
PACKAGE_STRING = server 1.0
PACKAGE_TARNAME = server
PACKAGE_URL = 
PACKAGE_VERSION = 1.0
PATH_SEPARATOR = :
SET_MAKE = 
SHELL = /bin/bash
STRIP = 
VERSION = 1.0
abs_builddir = /home/fu9ang/teachserver
abs_srcdir = /home/fu9ang/teachserver
abs_top_builddir = /home/fu9ang/teachserver
abs_top_srcdir = /home/fu9ang/teachserver
ac_ct_CC = gcc
ac_ct_CXX = g++
am__include = include
am__leading_dot = .
am__quote = 
am__tar = $${TAR-tar} chof - "$$tardir"
am__untar = $${TAR-tar} xf -
bindir = ${exec_prefix}/bin
build_alias = 
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = ${prefix}
host_alias = 
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = ${SHELL} /home/fu9ang/teachserver/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
mkdir_p = /bin/mkdir -p
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /usr/local
program_transform_name = s,x,x,
psdir = ${docdir}
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
sysconfdir = ${prefix}/etc
target_alias = 
top_build_prefix = 
top_builddir = .
top_srcdir = .
AUTOMAKE_OPTIONS = gnu
INCLUDES = -I./handler -I./content
server_LDADD = -lglog -lpthread -llua5.2 -lev -ldl -lrt -lmysqlcppconn
server_LDFLAGS = -g -Wall -Werror
server_CFLAGS = -g -Wall -Werror
server_CPPFLAGS = -g -Wall -Werror
server_SOURCES = ./main.cpp ./config.h ./Single.cpp ./QueueT.h ./Evloop.h ./SendTask.h ./ProcessManager.h ./Config.cpp ./Mutex.h ./handler/HandleMessage.cpp ./handler/HandleBuildHouse.cpp ./handler/HandleExercise.cpp ./handler/HandlePuzzle.cpp ./handler/HandleCartoon.cpp ./handler/HandleSprite.cpp ./handler/HandleMessage.h ./handler/HandleClassRoom.cpp ./ThreadPool.h ./twomapT.h ./database.h ./content/teacher.cpp ./content/courseitem.cpp ./content/roommanager.cpp ./content/course.cpp ./content/courseitem.h ./content/student.cpp ./content/room.h ./content/teacher.h ./content/student.h ./content/course.h ./content/game.cpp ./content/grade.h ./content/grade.cpp ./content/LoginCheck.cpp ./content/room.cpp ./content/roommanager.h ./content/LoginCheck.h ./content/game.h ./ThreadPool.cpp ./Sock.h ./database.cpp ./SQL.h ./protocol.h ./Buf.h ./PoolT.h ./Single.h ./task.h ./Evloop.cpp ./RecvTask.cpp ./AtomicT.h ./SendTask.cpp ./ProcessManager.cpp ./Config.h ./RecvTask.h ./Sock.c
all: config.h
	$(MAKE) $(AM_MAKEFLAGS) all-am

.SUFFIXES:
.SUFFIXES: .c .cpp .o .obj
am--refresh: Makefile
	@:
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      echo ' cd $(srcdir) && $(AUTOMAKE) --gnu'; \
	      $(am__cd) $(srcdir) && $(AUTOMAKE) --gnu \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --gnu Makefile'; \
	$(am__cd) $(top_srcdir) && \
	  $(AUTOMAKE) --gnu Makefile
.PRECIOUS: Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    echo ' $(SHELL) ./config.status'; \
	    $(SHELL) ./config.status;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck

$(top_srcdir)/configure:  $(am__configure_deps)
	$(am__cd) $(srcdir) && $(AUTOCONF)
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	$(am__cd) $(srcdir) && $(ACLOCAL) $(ACLOCAL_AMFLAGS)
$(am__aclocal_m4_deps):

config.h: stamp-h1
	@if test ! -f $@; then rm -f stamp-h1; else :; fi
	@if test ! -f $@; then $(MAKE) $(AM_MAKEFLAGS) stamp-h1; else :; fi

stamp-h1: $(srcdir)/config.h.in $(top_builddir)/config.status
	@rm -f stamp-h1
	cd $(top_builddir) && $(SHELL) ./config.status config.h
$(srcdir)/config.h.in:  $(am__configure_deps) 
	($(am__cd) $(top_srcdir) && $(AUTOHEADER))
	rm -f stamp-h1
	touch $@

distclean-hdr:
	-rm -f config.h stamp-h1
install-binPROGRAMS: $(bin_PROGRAMS)
	@$(NORMAL_INSTALL)
	test -z "$(bindir)" || $(MKDIR_P) "$(DESTDIR)$(bindir)"
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	for p in $$list; do echo "$$p $$p"; done | \
	sed 's/$(EXEEXT)$$//' | \
	while read p p1; do if test -f $$p; \
	  then echo "$$p"; echo "$$p"; else :; fi; \
	done | \
	sed -e 'p;s,.*/,,;n;h' -e 's|.*|.|' \
	    -e 'p;x;s,.*/,,;s/$(EXEEXT)$$//;$(transform);s/$$/$(EXEEXT)/' | \
	sed 'N;N;N;s,\n, ,g' | \
	$(AWK) 'BEGIN { files["."] = ""; dirs["."] = 1 } \
	  { d=$$3; if (dirs[d] != 1) { print "d", d; dirs[d] = 1 } \
	    if ($$2 == $$4) files[d] = files[d] " " $$1; \
	    else { print "f", $$3 "/" $$4, $$1; } } \
	  END { for (d in files) print "f", d, files[d] }' | \
	while read type dir files; do \
	    if test "$$dir" = .; then dir=; else dir=/$$dir; fi; \
	    test -z "$$files" || { \
	      echo " $(INSTALL_PROGRAM_ENV) $(INSTALL_PROGRAM) $$files '$(DESTDIR)$(bindir)$$dir'"; \
	      $(INSTALL_PROGRAM_ENV) $(INSTALL_PROGRAM) $$files "$(DESTDIR)$(bindir)$$dir" || exit $$?; \
	    } \
	; done

uninstall-binPROGRAMS:
	@$(NORMAL_UNINSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	files=`for p in $$list; do echo "$$p"; done | \
	  sed -e 'h;s,^.*/,,;s/$(EXEEXT)$$//;$(transform)' \
	      -e 's/$$/$(EXEEXT)/' `; \
	test -n "$$list" || exit 0; \
	echo " ( cd '$(DESTDIR)$(bindir)' && rm -f" $$files ")"; \
	cd "$(DESTDIR)$(bindir)" && rm -f $$files

clean-binPROGRAMS:
	-test -z "$(bin_PROGRAMS)" || rm -f $(bin_PROGRAMS)
server$(EXEEXT): $(server_OBJECTS) $(server_DEPENDENCIES) $(EXTRA_server_DEPENDENCIES) 
	@rm -f server$(EXEEXT)
	$(server_LINK) $(server_OBJECTS) $(server_LDADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT)

distclean-compile:
	-rm -f *.tab.c

include ./$(DEPDIR)/server-Config.Po
include ./$(DEPDIR)/server-Evloop.Po
include ./$(DEPDIR)/server-HandleBuildHouse.Po
include ./$(DEPDIR)/server-HandleCartoon.Po
include ./$(DEPDIR)/server-HandleClassRoom.Po
include ./$(DEPDIR)/server-HandleExercise.Po
include ./$(DEPDIR)/server-HandleMessage.Po
include ./$(DEPDIR)/server-HandlePuzzle.Po
include ./$(DEPDIR)/server-HandleSprite.Po
include ./$(DEPDIR)/server-LoginCheck.Po
include ./$(DEPDIR)/server-ProcessManager.Po
include ./$(DEPDIR)/server-RecvTask.Po
include ./$(DEPDIR)/server-SendTask.Po
include ./$(DEPDIR)/server-Single.Po
include ./$(DEPDIR)/server-Sock.Po
include ./$(DEPDIR)/server-ThreadPool.Po
include ./$(DEPDIR)/server-course.Po
include ./$(DEPDIR)/server-courseitem.Po
include ./$(DEPDIR)/server-database.Po
include ./$(DEPDIR)/server-game.Po
include ./$(DEPDIR)/server-grade.Po
include ./$(DEPDIR)/server-main.Po
include ./$(DEPDIR)/server-room.Po
include ./$(DEPDIR)/server-roommanager.Po
include ./$(DEPDIR)/server-student.Po
include ./$(DEPDIR)/server-teacher.Po

.c.o:
	$(COMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ $<
	$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(COMPILE) -c $<

.c.obj:
	$(COMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ `$(CYGPATH_W) '$<'`
	$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(COMPILE) -c `$(CYGPATH_W) '$<'`

server-Sock.o: ./Sock.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(server_CPPFLAGS) $(CPPFLAGS) $(server_CFLAGS) $(CFLAGS) -MT server-Sock.o -MD -MP -MF $(DEPDIR)/server-Sock.Tpo -c -o server-Sock.o `test -f './Sock.c' || echo '$(srcdir)/'`./Sock.c
	$(am__mv) $(DEPDIR)/server-Sock.Tpo $(DEPDIR)/server-Sock.Po
#	source='./Sock.c' object='server-Sock.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(server_CPPFLAGS) $(CPPFLAGS) $(server_CFLAGS) $(CFLAGS) -c -o server-Sock.o `test -f './Sock.c' || echo '$(srcdir)/'`./Sock.c

server-Sock.obj: ./Sock.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(server_CPPFLAGS) $(CPPFLAGS) $(server_CFLAGS) $(CFLAGS) -MT server-Sock.obj -MD -MP -MF $(DEPDIR)/server-Sock.Tpo -c -o server-Sock.obj `if test -f './Sock.c'; then $(CYGPATH_W) './Sock.c'; else $(CYGPATH_W) '$(srcdir)/./Sock.c'; fi`
	$(am__mv) $(DEPDIR)/server-Sock.Tpo $(DEPDIR)/server-Sock.Po
#	source='./Sock.c' object='server-Sock.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(server_CPPFLAGS) $(CPPFLAGS) $(server_CFLAGS) $(CFLAGS) -c -o server-Sock.obj `if test -f './Sock.c'; then $(CYGPATH_W) './Sock.c'; else $(CYGPATH_W) '$(srcdir)/./Sock.c'; fi`

.cpp.o:
	$(CXXCOMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ $<
	$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXXCOMPILE) -c -o $@ $<

.cpp.obj:
	$(CXXCOMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ `$(CYGPATH_W) '$<'`
	$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXXCOMPILE) -c -o $@ `$(CYGPATH_W) '$<'`

server-main.o: ./main.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(server_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT server-main.o -MD -MP -MF $(DEPDIR)/server-main.Tpo -c -o server-main.o `test -f './main.cpp' || echo '$(srcdir)/'`./main.cpp
	$(am__mv) $(DEPDIR)/server-main.Tpo $(DEPDIR)/server-main.Po
#	source='./main.cpp' object='server-main.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(server_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o server-main.o `test -f './main.cpp' || echo '$(srcdir)/'`./main.cpp

server-main.obj: ./main.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(server_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT server-main.obj -MD -MP -MF $(DEPDIR)/server-main.Tpo -c -o server-main.obj `if test -f './main.cpp'; then $(CYGPATH_W) './main.cpp'; else $(CYGPATH_W) '$(srcdir)/./main.cpp'; fi`
	$(am__mv) $(DEPDIR)/server-main.Tpo $(DEPDIR)/server-main.Po
#	source='./main.cpp' object='server-main.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(server_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o server-main.obj `if test -f './main.cpp'; then $(CYGPATH_W) './main.cpp'; else $(CYGPATH_W) '$(srcdir)/./main.cpp'; fi`

server-Single.o: ./Single.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(server_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT server-Single.o -MD -MP -MF $(DEPDIR)/server-Single.Tpo -c -o server-Single.o `test -f './Single.cpp' || echo '$(srcdir)/'`./Single.cpp
	$(am__mv) $(DEPDIR)/server-Single.Tpo $(DEPDIR)/server-Single.Po
#	source='./Single.cpp' object='server-Single.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(server_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o server-Single.o `test -f './Single.cpp' || echo '$(srcdir)/'`./Single.cpp

server-Single.obj: ./Single.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(server_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT server-Single.obj -MD -MP -MF $(DEPDIR)/server-Single.Tpo -c -o server-Single.obj `if test -f './Single.cpp'; then $(CYGPATH_W) './Single.cpp'; else $(CYGPATH_W) '$(srcdir)/./Single.cpp'; fi`
	$(am__mv) $(DEPDIR)/server-Single.Tpo $(DEPDIR)/server-Single.Po
#	source='./Single.cpp' object='server-Single.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(server_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o server-Single.obj `if test -f './Single.cpp'; then $(CYGPATH_W) './Single.cpp'; else $(CYGPATH_W) '$(srcdir)/./Single.cpp'; fi`

server-Config.o: ./Config.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(server_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT server-Config.o -MD -MP -MF $(DEPDIR)/server-Config.Tpo -c -o server-Config.o `test -f './Config.cpp' || echo '$(srcdir)/'`./Config.cpp
	$(am__mv) $(DEPDIR)/server-Config.Tpo $(DEPDIR)/server-Config.Po
#	source='./Config.cpp' object='server-Config.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(server_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o server-Config.o `test -f './Config.cpp' || echo '$(srcdir)/'`./Config.cpp

server-Config.obj: ./Config.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(server_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT server-Config.obj -MD -MP -MF $(DEPDIR)/server-Config.Tpo -c -o server-Config.obj `if test -f './Config.cpp'; then $(CYGPATH_W) './Config.cpp'; else $(CYGPATH_W) '$(srcdir)/./Config.cpp'; fi`
	$(am__mv) $(DEPDIR)/server-Config.Tpo $(DEPDIR)/server-Config.Po
#	source='./Config.cpp' object='server-Config.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(server_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o server-Config.obj `if test -f './Config.cpp'; then $(CYGPATH_W) './Config.cpp'; else $(CYGPATH_W) '$(srcdir)/./Config.cpp'; fi`

server-HandleMessage.o: ./handler/HandleMessage.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(server_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT server-HandleMessage.o -MD -MP -MF $(DEPDIR)/server-HandleMessage.Tpo -c -o server-HandleMessage.o `test -f './handler/HandleMessage.cpp' || echo '$(srcdir)/'`./handler/HandleMessage.cpp
	$(am__mv) $(DEPDIR)/server-HandleMessage.Tpo $(DEPDIR)/server-HandleMessage.Po
#	source='./handler/HandleMessage.cpp' object='server-HandleMessage.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(server_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o server-HandleMessage.o `test -f './handler/HandleMessage.cpp' || echo '$(srcdir)/'`./handler/HandleMessage.cpp

server-HandleMessage.obj: ./handler/HandleMessage.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(server_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT server-HandleMessage.obj -MD -MP -MF $(DEPDIR)/server-HandleMessage.Tpo -c -o server-HandleMessage.obj `if test -f './handler/HandleMessage.cpp'; then $(CYGPATH_W) './handler/HandleMessage.cpp'; else $(CYGPATH_W) '$(srcdir)/./handler/HandleMessage.cpp'; fi`
	$(am__mv) $(DEPDIR)/server-HandleMessage.Tpo $(DEPDIR)/server-HandleMessage.Po
#	source='./handler/HandleMessage.cpp' object='server-HandleMessage.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(server_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o server-HandleMessage.obj `if test -f './handler/HandleMessage.cpp'; then $(CYGPATH_W) './handler/HandleMessage.cpp'; else $(CYGPATH_W) '$(srcdir)/./handler/HandleMessage.cpp'; fi`

server-HandleBuildHouse.o: ./handler/HandleBuildHouse.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(server_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT server-HandleBuildHouse.o -MD -MP -MF $(DEPDIR)/server-HandleBuildHouse.Tpo -c -o server-HandleBuildHouse.o `test -f './handler/HandleBuildHouse.cpp' || echo '$(srcdir)/'`./handler/HandleBuildHouse.cpp
	$(am__mv) $(DEPDIR)/server-HandleBuildHouse.Tpo $(DEPDIR)/server-HandleBuildHouse.Po
#	source='./handler/HandleBuildHouse.cpp' object='server-HandleBuildHouse.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(server_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o server-HandleBuildHouse.o `test -f './handler/HandleBuildHouse.cpp' || echo '$(srcdir)/'`./handler/HandleBuildHouse.cpp

server-HandleBuildHouse.obj: ./handler/HandleBuildHouse.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(server_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT server-HandleBuildHouse.obj -MD -MP -MF $(DEPDIR)/server-HandleBuildHouse.Tpo -c -o server-HandleBuildHouse.obj `if test -f './handler/HandleBuildHouse.cpp'; then $(CYGPATH_W) './handler/HandleBuildHouse.cpp'; else $(CYGPATH_W) '$(srcdir)/./handler/HandleBuildHouse.cpp'; fi`
	$(am__mv) $(DEPDIR)/server-HandleBuildHouse.Tpo $(DEPDIR)/server-HandleBuildHouse.Po
#	source='./handler/HandleBuildHouse.cpp' object='server-HandleBuildHouse.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(server_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o server-HandleBuildHouse.obj `if test -f './handler/HandleBuildHouse.cpp'; then $(CYGPATH_W) './handler/HandleBuildHouse.cpp'; else $(CYGPATH_W) '$(srcdir)/./handler/HandleBuildHouse.cpp'; fi`

server-HandleExercise.o: ./handler/HandleExercise.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(server_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT server-HandleExercise.o -MD -MP -MF $(DEPDIR)/server-HandleExercise.Tpo -c -o server-HandleExercise.o `test -f './handler/HandleExercise.cpp' || echo '$(srcdir)/'`./handler/HandleExercise.cpp
	$(am__mv) $(DEPDIR)/server-HandleExercise.Tpo $(DEPDIR)/server-HandleExercise.Po
#	source='./handler/HandleExercise.cpp' object='server-HandleExercise.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(server_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o server-HandleExercise.o `test -f './handler/HandleExercise.cpp' || echo '$(srcdir)/'`./handler/HandleExercise.cpp

server-HandleExercise.obj: ./handler/HandleExercise.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(server_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT server-HandleExercise.obj -MD -MP -MF $(DEPDIR)/server-HandleExercise.Tpo -c -o server-HandleExercise.obj `if test -f './handler/HandleExercise.cpp'; then $(CYGPATH_W) './handler/HandleExercise.cpp'; else $(CYGPATH_W) '$(srcdir)/./handler/HandleExercise.cpp'; fi`
	$(am__mv) $(DEPDIR)/server-HandleExercise.Tpo $(DEPDIR)/server-HandleExercise.Po
#	source='./handler/HandleExercise.cpp' object='server-HandleExercise.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(server_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o server-HandleExercise.obj `if test -f './handler/HandleExercise.cpp'; then $(CYGPATH_W) './handler/HandleExercise.cpp'; else $(CYGPATH_W) '$(srcdir)/./handler/HandleExercise.cpp'; fi`

server-HandlePuzzle.o: ./handler/HandlePuzzle.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(server_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT server-HandlePuzzle.o -MD -MP -MF $(DEPDIR)/server-HandlePuzzle.Tpo -c -o server-HandlePuzzle.o `test -f './handler/HandlePuzzle.cpp' || echo '$(srcdir)/'`./handler/HandlePuzzle.cpp
	$(am__mv) $(DEPDIR)/server-HandlePuzzle.Tpo $(DEPDIR)/server-HandlePuzzle.Po
#	source='./handler/HandlePuzzle.cpp' object='server-HandlePuzzle.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(server_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o server-HandlePuzzle.o `test -f './handler/HandlePuzzle.cpp' || echo '$(srcdir)/'`./handler/HandlePuzzle.cpp

server-HandlePuzzle.obj: ./handler/HandlePuzzle.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(server_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT server-HandlePuzzle.obj -MD -MP -MF $(DEPDIR)/server-HandlePuzzle.Tpo -c -o server-HandlePuzzle.obj `if test -f './handler/HandlePuzzle.cpp'; then $(CYGPATH_W) './handler/HandlePuzzle.cpp'; else $(CYGPATH_W) '$(srcdir)/./handler/HandlePuzzle.cpp'; fi`
	$(am__mv) $(DEPDIR)/server-HandlePuzzle.Tpo $(DEPDIR)/server-HandlePuzzle.Po
#	source='./handler/HandlePuzzle.cpp' object='server-HandlePuzzle.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(server_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o server-HandlePuzzle.obj `if test -f './handler/HandlePuzzle.cpp'; then $(CYGPATH_W) './handler/HandlePuzzle.cpp'; else $(CYGPATH_W) '$(srcdir)/./handler/HandlePuzzle.cpp'; fi`

server-HandleCartoon.o: ./handler/HandleCartoon.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(server_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT server-HandleCartoon.o -MD -MP -MF $(DEPDIR)/server-HandleCartoon.Tpo -c -o server-HandleCartoon.o `test -f './handler/HandleCartoon.cpp' || echo '$(srcdir)/'`./handler/HandleCartoon.cpp
	$(am__mv) $(DEPDIR)/server-HandleCartoon.Tpo $(DEPDIR)/server-HandleCartoon.Po
#	source='./handler/HandleCartoon.cpp' object='server-HandleCartoon.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(server_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o server-HandleCartoon.o `test -f './handler/HandleCartoon.cpp' || echo '$(srcdir)/'`./handler/HandleCartoon.cpp

server-HandleCartoon.obj: ./handler/HandleCartoon.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(server_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT server-HandleCartoon.obj -MD -MP -MF $(DEPDIR)/server-HandleCartoon.Tpo -c -o server-HandleCartoon.obj `if test -f './handler/HandleCartoon.cpp'; then $(CYGPATH_W) './handler/HandleCartoon.cpp'; else $(CYGPATH_W) '$(srcdir)/./handler/HandleCartoon.cpp'; fi`
	$(am__mv) $(DEPDIR)/server-HandleCartoon.Tpo $(DEPDIR)/server-HandleCartoon.Po
#	source='./handler/HandleCartoon.cpp' object='server-HandleCartoon.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(server_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o server-HandleCartoon.obj `if test -f './handler/HandleCartoon.cpp'; then $(CYGPATH_W) './handler/HandleCartoon.cpp'; else $(CYGPATH_W) '$(srcdir)/./handler/HandleCartoon.cpp'; fi`

server-HandleSprite.o: ./handler/HandleSprite.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(server_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT server-HandleSprite.o -MD -MP -MF $(DEPDIR)/server-HandleSprite.Tpo -c -o server-HandleSprite.o `test -f './handler/HandleSprite.cpp' || echo '$(srcdir)/'`./handler/HandleSprite.cpp
	$(am__mv) $(DEPDIR)/server-HandleSprite.Tpo $(DEPDIR)/server-HandleSprite.Po
#	source='./handler/HandleSprite.cpp' object='server-HandleSprite.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(server_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o server-HandleSprite.o `test -f './handler/HandleSprite.cpp' || echo '$(srcdir)/'`./handler/HandleSprite.cpp

server-HandleSprite.obj: ./handler/HandleSprite.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(server_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT server-HandleSprite.obj -MD -MP -MF $(DEPDIR)/server-HandleSprite.Tpo -c -o server-HandleSprite.obj `if test -f './handler/HandleSprite.cpp'; then $(CYGPATH_W) './handler/HandleSprite.cpp'; else $(CYGPATH_W) '$(srcdir)/./handler/HandleSprite.cpp'; fi`
	$(am__mv) $(DEPDIR)/server-HandleSprite.Tpo $(DEPDIR)/server-HandleSprite.Po
#	source='./handler/HandleSprite.cpp' object='server-HandleSprite.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(server_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o server-HandleSprite.obj `if test -f './handler/HandleSprite.cpp'; then $(CYGPATH_W) './handler/HandleSprite.cpp'; else $(CYGPATH_W) '$(srcdir)/./handler/HandleSprite.cpp'; fi`

server-HandleClassRoom.o: ./handler/HandleClassRoom.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(server_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT server-HandleClassRoom.o -MD -MP -MF $(DEPDIR)/server-HandleClassRoom.Tpo -c -o server-HandleClassRoom.o `test -f './handler/HandleClassRoom.cpp' || echo '$(srcdir)/'`./handler/HandleClassRoom.cpp
	$(am__mv) $(DEPDIR)/server-HandleClassRoom.Tpo $(DEPDIR)/server-HandleClassRoom.Po
#	source='./handler/HandleClassRoom.cpp' object='server-HandleClassRoom.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(server_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o server-HandleClassRoom.o `test -f './handler/HandleClassRoom.cpp' || echo '$(srcdir)/'`./handler/HandleClassRoom.cpp

server-HandleClassRoom.obj: ./handler/HandleClassRoom.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(server_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT server-HandleClassRoom.obj -MD -MP -MF $(DEPDIR)/server-HandleClassRoom.Tpo -c -o server-HandleClassRoom.obj `if test -f './handler/HandleClassRoom.cpp'; then $(CYGPATH_W) './handler/HandleClassRoom.cpp'; else $(CYGPATH_W) '$(srcdir)/./handler/HandleClassRoom.cpp'; fi`
	$(am__mv) $(DEPDIR)/server-HandleClassRoom.Tpo $(DEPDIR)/server-HandleClassRoom.Po
#	source='./handler/HandleClassRoom.cpp' object='server-HandleClassRoom.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(server_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o server-HandleClassRoom.obj `if test -f './handler/HandleClassRoom.cpp'; then $(CYGPATH_W) './handler/HandleClassRoom.cpp'; else $(CYGPATH_W) '$(srcdir)/./handler/HandleClassRoom.cpp'; fi`

server-teacher.o: ./content/teacher.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(server_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT server-teacher.o -MD -MP -MF $(DEPDIR)/server-teacher.Tpo -c -o server-teacher.o `test -f './content/teacher.cpp' || echo '$(srcdir)/'`./content/teacher.cpp
	$(am__mv) $(DEPDIR)/server-teacher.Tpo $(DEPDIR)/server-teacher.Po
#	source='./content/teacher.cpp' object='server-teacher.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(server_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o server-teacher.o `test -f './content/teacher.cpp' || echo '$(srcdir)/'`./content/teacher.cpp

server-teacher.obj: ./content/teacher.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(server_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT server-teacher.obj -MD -MP -MF $(DEPDIR)/server-teacher.Tpo -c -o server-teacher.obj `if test -f './content/teacher.cpp'; then $(CYGPATH_W) './content/teacher.cpp'; else $(CYGPATH_W) '$(srcdir)/./content/teacher.cpp'; fi`
	$(am__mv) $(DEPDIR)/server-teacher.Tpo $(DEPDIR)/server-teacher.Po
#	source='./content/teacher.cpp' object='server-teacher.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(server_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o server-teacher.obj `if test -f './content/teacher.cpp'; then $(CYGPATH_W) './content/teacher.cpp'; else $(CYGPATH_W) '$(srcdir)/./content/teacher.cpp'; fi`

server-courseitem.o: ./content/courseitem.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(server_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT server-courseitem.o -MD -MP -MF $(DEPDIR)/server-courseitem.Tpo -c -o server-courseitem.o `test -f './content/courseitem.cpp' || echo '$(srcdir)/'`./content/courseitem.cpp
	$(am__mv) $(DEPDIR)/server-courseitem.Tpo $(DEPDIR)/server-courseitem.Po
#	source='./content/courseitem.cpp' object='server-courseitem.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(server_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o server-courseitem.o `test -f './content/courseitem.cpp' || echo '$(srcdir)/'`./content/courseitem.cpp

server-courseitem.obj: ./content/courseitem.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(server_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT server-courseitem.obj -MD -MP -MF $(DEPDIR)/server-courseitem.Tpo -c -o server-courseitem.obj `if test -f './content/courseitem.cpp'; then $(CYGPATH_W) './content/courseitem.cpp'; else $(CYGPATH_W) '$(srcdir)/./content/courseitem.cpp'; fi`
	$(am__mv) $(DEPDIR)/server-courseitem.Tpo $(DEPDIR)/server-courseitem.Po
#	source='./content/courseitem.cpp' object='server-courseitem.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(server_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o server-courseitem.obj `if test -f './content/courseitem.cpp'; then $(CYGPATH_W) './content/courseitem.cpp'; else $(CYGPATH_W) '$(srcdir)/./content/courseitem.cpp'; fi`

server-roommanager.o: ./content/roommanager.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(server_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT server-roommanager.o -MD -MP -MF $(DEPDIR)/server-roommanager.Tpo -c -o server-roommanager.o `test -f './content/roommanager.cpp' || echo '$(srcdir)/'`./content/roommanager.cpp
	$(am__mv) $(DEPDIR)/server-roommanager.Tpo $(DEPDIR)/server-roommanager.Po
#	source='./content/roommanager.cpp' object='server-roommanager.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(server_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o server-roommanager.o `test -f './content/roommanager.cpp' || echo '$(srcdir)/'`./content/roommanager.cpp

server-roommanager.obj: ./content/roommanager.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(server_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT server-roommanager.obj -MD -MP -MF $(DEPDIR)/server-roommanager.Tpo -c -o server-roommanager.obj `if test -f './content/roommanager.cpp'; then $(CYGPATH_W) './content/roommanager.cpp'; else $(CYGPATH_W) '$(srcdir)/./content/roommanager.cpp'; fi`
	$(am__mv) $(DEPDIR)/server-roommanager.Tpo $(DEPDIR)/server-roommanager.Po
#	source='./content/roommanager.cpp' object='server-roommanager.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(server_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o server-roommanager.obj `if test -f './content/roommanager.cpp'; then $(CYGPATH_W) './content/roommanager.cpp'; else $(CYGPATH_W) '$(srcdir)/./content/roommanager.cpp'; fi`

server-course.o: ./content/course.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(server_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT server-course.o -MD -MP -MF $(DEPDIR)/server-course.Tpo -c -o server-course.o `test -f './content/course.cpp' || echo '$(srcdir)/'`./content/course.cpp
	$(am__mv) $(DEPDIR)/server-course.Tpo $(DEPDIR)/server-course.Po
#	source='./content/course.cpp' object='server-course.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(server_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o server-course.o `test -f './content/course.cpp' || echo '$(srcdir)/'`./content/course.cpp

server-course.obj: ./content/course.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(server_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT server-course.obj -MD -MP -MF $(DEPDIR)/server-course.Tpo -c -o server-course.obj `if test -f './content/course.cpp'; then $(CYGPATH_W) './content/course.cpp'; else $(CYGPATH_W) '$(srcdir)/./content/course.cpp'; fi`
	$(am__mv) $(DEPDIR)/server-course.Tpo $(DEPDIR)/server-course.Po
#	source='./content/course.cpp' object='server-course.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(server_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o server-course.obj `if test -f './content/course.cpp'; then $(CYGPATH_W) './content/course.cpp'; else $(CYGPATH_W) '$(srcdir)/./content/course.cpp'; fi`

server-student.o: ./content/student.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(server_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT server-student.o -MD -MP -MF $(DEPDIR)/server-student.Tpo -c -o server-student.o `test -f './content/student.cpp' || echo '$(srcdir)/'`./content/student.cpp
	$(am__mv) $(DEPDIR)/server-student.Tpo $(DEPDIR)/server-student.Po
#	source='./content/student.cpp' object='server-student.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(server_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o server-student.o `test -f './content/student.cpp' || echo '$(srcdir)/'`./content/student.cpp

server-student.obj: ./content/student.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(server_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT server-student.obj -MD -MP -MF $(DEPDIR)/server-student.Tpo -c -o server-student.obj `if test -f './content/student.cpp'; then $(CYGPATH_W) './content/student.cpp'; else $(CYGPATH_W) '$(srcdir)/./content/student.cpp'; fi`
	$(am__mv) $(DEPDIR)/server-student.Tpo $(DEPDIR)/server-student.Po
#	source='./content/student.cpp' object='server-student.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(server_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o server-student.obj `if test -f './content/student.cpp'; then $(CYGPATH_W) './content/student.cpp'; else $(CYGPATH_W) '$(srcdir)/./content/student.cpp'; fi`

server-game.o: ./content/game.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(server_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT server-game.o -MD -MP -MF $(DEPDIR)/server-game.Tpo -c -o server-game.o `test -f './content/game.cpp' || echo '$(srcdir)/'`./content/game.cpp
	$(am__mv) $(DEPDIR)/server-game.Tpo $(DEPDIR)/server-game.Po
#	source='./content/game.cpp' object='server-game.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(server_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o server-game.o `test -f './content/game.cpp' || echo '$(srcdir)/'`./content/game.cpp

server-game.obj: ./content/game.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(server_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT server-game.obj -MD -MP -MF $(DEPDIR)/server-game.Tpo -c -o server-game.obj `if test -f './content/game.cpp'; then $(CYGPATH_W) './content/game.cpp'; else $(CYGPATH_W) '$(srcdir)/./content/game.cpp'; fi`
	$(am__mv) $(DEPDIR)/server-game.Tpo $(DEPDIR)/server-game.Po
#	source='./content/game.cpp' object='server-game.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(server_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o server-game.obj `if test -f './content/game.cpp'; then $(CYGPATH_W) './content/game.cpp'; else $(CYGPATH_W) '$(srcdir)/./content/game.cpp'; fi`

server-grade.o: ./content/grade.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(server_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT server-grade.o -MD -MP -MF $(DEPDIR)/server-grade.Tpo -c -o server-grade.o `test -f './content/grade.cpp' || echo '$(srcdir)/'`./content/grade.cpp
	$(am__mv) $(DEPDIR)/server-grade.Tpo $(DEPDIR)/server-grade.Po
#	source='./content/grade.cpp' object='server-grade.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(server_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o server-grade.o `test -f './content/grade.cpp' || echo '$(srcdir)/'`./content/grade.cpp

server-grade.obj: ./content/grade.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(server_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT server-grade.obj -MD -MP -MF $(DEPDIR)/server-grade.Tpo -c -o server-grade.obj `if test -f './content/grade.cpp'; then $(CYGPATH_W) './content/grade.cpp'; else $(CYGPATH_W) '$(srcdir)/./content/grade.cpp'; fi`
	$(am__mv) $(DEPDIR)/server-grade.Tpo $(DEPDIR)/server-grade.Po
#	source='./content/grade.cpp' object='server-grade.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(server_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o server-grade.obj `if test -f './content/grade.cpp'; then $(CYGPATH_W) './content/grade.cpp'; else $(CYGPATH_W) '$(srcdir)/./content/grade.cpp'; fi`

server-LoginCheck.o: ./content/LoginCheck.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(server_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT server-LoginCheck.o -MD -MP -MF $(DEPDIR)/server-LoginCheck.Tpo -c -o server-LoginCheck.o `test -f './content/LoginCheck.cpp' || echo '$(srcdir)/'`./content/LoginCheck.cpp
	$(am__mv) $(DEPDIR)/server-LoginCheck.Tpo $(DEPDIR)/server-LoginCheck.Po
#	source='./content/LoginCheck.cpp' object='server-LoginCheck.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(server_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o server-LoginCheck.o `test -f './content/LoginCheck.cpp' || echo '$(srcdir)/'`./content/LoginCheck.cpp

server-LoginCheck.obj: ./content/LoginCheck.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(server_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT server-LoginCheck.obj -MD -MP -MF $(DEPDIR)/server-LoginCheck.Tpo -c -o server-LoginCheck.obj `if test -f './content/LoginCheck.cpp'; then $(CYGPATH_W) './content/LoginCheck.cpp'; else $(CYGPATH_W) '$(srcdir)/./content/LoginCheck.cpp'; fi`
	$(am__mv) $(DEPDIR)/server-LoginCheck.Tpo $(DEPDIR)/server-LoginCheck.Po
#	source='./content/LoginCheck.cpp' object='server-LoginCheck.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(server_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o server-LoginCheck.obj `if test -f './content/LoginCheck.cpp'; then $(CYGPATH_W) './content/LoginCheck.cpp'; else $(CYGPATH_W) '$(srcdir)/./content/LoginCheck.cpp'; fi`

server-room.o: ./content/room.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(server_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT server-room.o -MD -MP -MF $(DEPDIR)/server-room.Tpo -c -o server-room.o `test -f './content/room.cpp' || echo '$(srcdir)/'`./content/room.cpp
	$(am__mv) $(DEPDIR)/server-room.Tpo $(DEPDIR)/server-room.Po
#	source='./content/room.cpp' object='server-room.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(server_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o server-room.o `test -f './content/room.cpp' || echo '$(srcdir)/'`./content/room.cpp

server-room.obj: ./content/room.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(server_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT server-room.obj -MD -MP -MF $(DEPDIR)/server-room.Tpo -c -o server-room.obj `if test -f './content/room.cpp'; then $(CYGPATH_W) './content/room.cpp'; else $(CYGPATH_W) '$(srcdir)/./content/room.cpp'; fi`
	$(am__mv) $(DEPDIR)/server-room.Tpo $(DEPDIR)/server-room.Po
#	source='./content/room.cpp' object='server-room.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(server_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o server-room.obj `if test -f './content/room.cpp'; then $(CYGPATH_W) './content/room.cpp'; else $(CYGPATH_W) '$(srcdir)/./content/room.cpp'; fi`

server-ThreadPool.o: ./ThreadPool.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(server_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT server-ThreadPool.o -MD -MP -MF $(DEPDIR)/server-ThreadPool.Tpo -c -o server-ThreadPool.o `test -f './ThreadPool.cpp' || echo '$(srcdir)/'`./ThreadPool.cpp
	$(am__mv) $(DEPDIR)/server-ThreadPool.Tpo $(DEPDIR)/server-ThreadPool.Po
#	source='./ThreadPool.cpp' object='server-ThreadPool.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(server_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o server-ThreadPool.o `test -f './ThreadPool.cpp' || echo '$(srcdir)/'`./ThreadPool.cpp

server-ThreadPool.obj: ./ThreadPool.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(server_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT server-ThreadPool.obj -MD -MP -MF $(DEPDIR)/server-ThreadPool.Tpo -c -o server-ThreadPool.obj `if test -f './ThreadPool.cpp'; then $(CYGPATH_W) './ThreadPool.cpp'; else $(CYGPATH_W) '$(srcdir)/./ThreadPool.cpp'; fi`
	$(am__mv) $(DEPDIR)/server-ThreadPool.Tpo $(DEPDIR)/server-ThreadPool.Po
#	source='./ThreadPool.cpp' object='server-ThreadPool.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(server_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o server-ThreadPool.obj `if test -f './ThreadPool.cpp'; then $(CYGPATH_W) './ThreadPool.cpp'; else $(CYGPATH_W) '$(srcdir)/./ThreadPool.cpp'; fi`

server-database.o: ./database.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(server_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT server-database.o -MD -MP -MF $(DEPDIR)/server-database.Tpo -c -o server-database.o `test -f './database.cpp' || echo '$(srcdir)/'`./database.cpp
	$(am__mv) $(DEPDIR)/server-database.Tpo $(DEPDIR)/server-database.Po
#	source='./database.cpp' object='server-database.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(server_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o server-database.o `test -f './database.cpp' || echo '$(srcdir)/'`./database.cpp

server-database.obj: ./database.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(server_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT server-database.obj -MD -MP -MF $(DEPDIR)/server-database.Tpo -c -o server-database.obj `if test -f './database.cpp'; then $(CYGPATH_W) './database.cpp'; else $(CYGPATH_W) '$(srcdir)/./database.cpp'; fi`
	$(am__mv) $(DEPDIR)/server-database.Tpo $(DEPDIR)/server-database.Po
#	source='./database.cpp' object='server-database.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(server_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o server-database.obj `if test -f './database.cpp'; then $(CYGPATH_W) './database.cpp'; else $(CYGPATH_W) '$(srcdir)/./database.cpp'; fi`

server-Evloop.o: ./Evloop.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(server_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT server-Evloop.o -MD -MP -MF $(DEPDIR)/server-Evloop.Tpo -c -o server-Evloop.o `test -f './Evloop.cpp' || echo '$(srcdir)/'`./Evloop.cpp
	$(am__mv) $(DEPDIR)/server-Evloop.Tpo $(DEPDIR)/server-Evloop.Po
#	source='./Evloop.cpp' object='server-Evloop.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(server_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o server-Evloop.o `test -f './Evloop.cpp' || echo '$(srcdir)/'`./Evloop.cpp

server-Evloop.obj: ./Evloop.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(server_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT server-Evloop.obj -MD -MP -MF $(DEPDIR)/server-Evloop.Tpo -c -o server-Evloop.obj `if test -f './Evloop.cpp'; then $(CYGPATH_W) './Evloop.cpp'; else $(CYGPATH_W) '$(srcdir)/./Evloop.cpp'; fi`
	$(am__mv) $(DEPDIR)/server-Evloop.Tpo $(DEPDIR)/server-Evloop.Po
#	source='./Evloop.cpp' object='server-Evloop.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(server_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o server-Evloop.obj `if test -f './Evloop.cpp'; then $(CYGPATH_W) './Evloop.cpp'; else $(CYGPATH_W) '$(srcdir)/./Evloop.cpp'; fi`

server-RecvTask.o: ./RecvTask.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(server_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT server-RecvTask.o -MD -MP -MF $(DEPDIR)/server-RecvTask.Tpo -c -o server-RecvTask.o `test -f './RecvTask.cpp' || echo '$(srcdir)/'`./RecvTask.cpp
	$(am__mv) $(DEPDIR)/server-RecvTask.Tpo $(DEPDIR)/server-RecvTask.Po
#	source='./RecvTask.cpp' object='server-RecvTask.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(server_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o server-RecvTask.o `test -f './RecvTask.cpp' || echo '$(srcdir)/'`./RecvTask.cpp

server-RecvTask.obj: ./RecvTask.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(server_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT server-RecvTask.obj -MD -MP -MF $(DEPDIR)/server-RecvTask.Tpo -c -o server-RecvTask.obj `if test -f './RecvTask.cpp'; then $(CYGPATH_W) './RecvTask.cpp'; else $(CYGPATH_W) '$(srcdir)/./RecvTask.cpp'; fi`
	$(am__mv) $(DEPDIR)/server-RecvTask.Tpo $(DEPDIR)/server-RecvTask.Po
#	source='./RecvTask.cpp' object='server-RecvTask.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(server_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o server-RecvTask.obj `if test -f './RecvTask.cpp'; then $(CYGPATH_W) './RecvTask.cpp'; else $(CYGPATH_W) '$(srcdir)/./RecvTask.cpp'; fi`

server-SendTask.o: ./SendTask.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(server_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT server-SendTask.o -MD -MP -MF $(DEPDIR)/server-SendTask.Tpo -c -o server-SendTask.o `test -f './SendTask.cpp' || echo '$(srcdir)/'`./SendTask.cpp
	$(am__mv) $(DEPDIR)/server-SendTask.Tpo $(DEPDIR)/server-SendTask.Po
#	source='./SendTask.cpp' object='server-SendTask.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(server_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o server-SendTask.o `test -f './SendTask.cpp' || echo '$(srcdir)/'`./SendTask.cpp

server-SendTask.obj: ./SendTask.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(server_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT server-SendTask.obj -MD -MP -MF $(DEPDIR)/server-SendTask.Tpo -c -o server-SendTask.obj `if test -f './SendTask.cpp'; then $(CYGPATH_W) './SendTask.cpp'; else $(CYGPATH_W) '$(srcdir)/./SendTask.cpp'; fi`
	$(am__mv) $(DEPDIR)/server-SendTask.Tpo $(DEPDIR)/server-SendTask.Po
#	source='./SendTask.cpp' object='server-SendTask.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(server_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o server-SendTask.obj `if test -f './SendTask.cpp'; then $(CYGPATH_W) './SendTask.cpp'; else $(CYGPATH_W) '$(srcdir)/./SendTask.cpp'; fi`

server-ProcessManager.o: ./ProcessManager.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(server_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT server-ProcessManager.o -MD -MP -MF $(DEPDIR)/server-ProcessManager.Tpo -c -o server-ProcessManager.o `test -f './ProcessManager.cpp' || echo '$(srcdir)/'`./ProcessManager.cpp
	$(am__mv) $(DEPDIR)/server-ProcessManager.Tpo $(DEPDIR)/server-ProcessManager.Po
#	source='./ProcessManager.cpp' object='server-ProcessManager.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(server_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o server-ProcessManager.o `test -f './ProcessManager.cpp' || echo '$(srcdir)/'`./ProcessManager.cpp

server-ProcessManager.obj: ./ProcessManager.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(server_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT server-ProcessManager.obj -MD -MP -MF $(DEPDIR)/server-ProcessManager.Tpo -c -o server-ProcessManager.obj `if test -f './ProcessManager.cpp'; then $(CYGPATH_W) './ProcessManager.cpp'; else $(CYGPATH_W) '$(srcdir)/./ProcessManager.cpp'; fi`
	$(am__mv) $(DEPDIR)/server-ProcessManager.Tpo $(DEPDIR)/server-ProcessManager.Po
#	source='./ProcessManager.cpp' object='server-ProcessManager.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(server_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o server-ProcessManager.obj `if test -f './ProcessManager.cpp'; then $(CYGPATH_W) './ProcessManager.cpp'; else $(CYGPATH_W) '$(srcdir)/./ProcessManager.cpp'; fi`

ID: $(HEADERS) $(SOURCES) $(LISP) $(TAGS_FILES)
	list='$(SOURCES) $(HEADERS) $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	mkid -fID $$unique
tags: TAGS

TAGS:  $(HEADERS) $(SOURCES) config.h.in $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	set x; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS) config.h.in $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	shift; \
	if test -z "$(ETAGS_ARGS)$$*$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  if test $$# -gt 0; then \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      "$$@" $$unique; \
	  else \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      $$unique; \
	  fi; \
	fi
ctags: CTAGS
CTAGS:  $(HEADERS) $(SOURCES) config.h.in $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	list='$(SOURCES) $(HEADERS) config.h.in $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	test -z "$(CTAGS_ARGS)$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && $(am__cd) $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) "$$here"

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags

distdir: $(DISTFILES)
	$(am__remove_distdir)
	test -d "$(distdir)" || mkdir "$(distdir)"
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d "$(distdir)/$$file"; then \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -fpR $(srcdir)/$$file "$(distdir)$$dir" || exit 1; \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    cp -fpR $$d/$$file "$(distdir)$$dir" || exit 1; \
	  else \
	    test -f "$(distdir)/$$file" \
	    || cp -p $$d/$$file "$(distdir)/$$file" \
	    || exit 1; \
	  fi; \
	done
	-test -n "$(am__skip_mode_fix)" \
	|| find "$(distdir)" -type d ! -perm -755 \
		-exec chmod u+rwx,go+rx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec $(install_sh) -c -m a+r {} {} \; \
	|| chmod -R a+r "$(distdir)"
dist-gzip: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__remove_distdir)

dist-bzip2: distdir
	tardir=$(distdir) && $(am__tar) | BZIP2=$${BZIP2--9} bzip2 -c >$(distdir).tar.bz2
	$(am__remove_distdir)

dist-lzip: distdir
	tardir=$(distdir) && $(am__tar) | lzip -c $${LZIP_OPT--9} >$(distdir).tar.lz
	$(am__remove_distdir)

dist-lzma: distdir
	tardir=$(distdir) && $(am__tar) | lzma -9 -c >$(distdir).tar.lzma
	$(am__remove_distdir)

dist-xz: distdir
	tardir=$(distdir) && $(am__tar) | XZ_OPT=$${XZ_OPT--e} xz -c >$(distdir).tar.xz
	$(am__remove_distdir)

dist-tarZ: distdir
	tardir=$(distdir) && $(am__tar) | compress -c >$(distdir).tar.Z
	$(am__remove_distdir)

dist-shar: distdir
	shar $(distdir) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).shar.gz
	$(am__remove_distdir)

dist-zip: distdir
	-rm -f $(distdir).zip
	zip -rq $(distdir).zip $(distdir)
	$(am__remove_distdir)

dist dist-all: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__remove_distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	case '$(DIST_ARCHIVES)' in \
	*.tar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).tar.gz | $(am__untar) ;;\
	*.tar.bz2*) \
	  bzip2 -dc $(distdir).tar.bz2 | $(am__untar) ;;\
	*.tar.lzma*) \
	  lzma -dc $(distdir).tar.lzma | $(am__untar) ;;\
	*.tar.lz*) \
	  lzip -dc $(distdir).tar.lz | $(am__untar) ;;\
	*.tar.xz*) \
	  xz -dc $(distdir).tar.xz | $(am__untar) ;;\
	*.tar.Z*) \
	  uncompress -c $(distdir).tar.Z | $(am__untar) ;;\
	*.shar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).shar.gz | unshar ;;\
	*.zip*) \
	  unzip $(distdir).zip ;;\
	esac
	chmod -R a-w $(distdir); chmod a+w $(distdir)
	mkdir $(distdir)/_build
	mkdir $(distdir)/_inst
	chmod a-w $(distdir)
	test -d $(distdir)/_build || exit 0; \
	dc_install_base=`$(am__cd) $(distdir)/_inst && pwd | sed -e 's,^[^:\\/]:[\\/],/,'` \
	  && dc_destdir="$${TMPDIR-/tmp}/am-dc-$$$$/" \
	  && am__cwd=`pwd` \
	  && $(am__cd) $(distdir)/_build \
	  && ../configure --srcdir=.. --prefix="$$dc_install_base" \
	    $(AM_DISTCHECK_CONFIGURE_FLAGS) \
	    $(DISTCHECK_CONFIGURE_FLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) dvi \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) uninstall \
	  && $(MAKE) $(AM_MAKEFLAGS) distuninstallcheck_dir="$$dc_install_base" \
	        distuninstallcheck \
	  && chmod -R a-w "$$dc_install_base" \
	  && ({ \
	       (cd ../.. && umask 077 && mkdir "$$dc_destdir") \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" install \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" uninstall \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" \
	            distuninstallcheck_dir="$$dc_destdir" distuninstallcheck; \
	      } || { rm -rf "$$dc_destdir"; exit 1; }) \
	  && rm -rf "$$dc_destdir" \
	  && $(MAKE) $(AM_MAKEFLAGS) dist \
	  && rm -rf $(DIST_ARCHIVES) \
	  && $(MAKE) $(AM_MAKEFLAGS) distcleancheck \
	  && cd "$$am__cwd" \
	  || exit 1
	$(am__remove_distdir)
	@(echo "$(distdir) archives ready for distribution: "; \
	  list='$(DIST_ARCHIVES)'; for i in $$list; do echo $$i; done) | \
	  sed -e 1h -e 1s/./=/g -e 1p -e 1x -e '$$p' -e '$$x'
distuninstallcheck:
	@test -n '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: trying to run $@ with an empty' \
	       '$$(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	$(am__cd) '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: cannot chdir into $(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	test `$(am__distuninstallcheck_listfiles) | wc -l` -eq 0 \
	   || { echo "ERROR: files left after uninstall:" ; \
	        if test -n "$(DESTDIR)"; then \
	          echo "  (check DESTDIR support)"; \
	        fi ; \
	        $(distuninstallcheck_listfiles) ; \
	        exit 1; } >&2
distcleancheck: distclean
	@if test '$(srcdir)' = . ; then \
	  echo "ERROR: distcleancheck can only run from a VPATH build" ; \
	  exit 1 ; \
	fi
	@test `$(distcleancheck_listfiles) | wc -l` -eq 0 \
	  || { echo "ERROR: files left in build directory after distclean:" ; \
	       $(distcleancheck_listfiles) ; \
	       exit 1; } >&2
check-am: all-am
check: check-am
all-am: Makefile $(PROGRAMS) config.h
installdirs:
	for dir in "$(DESTDIR)$(bindir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	if test -z '$(STRIP)'; then \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	      install; \
	else \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	    "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'" install; \
	fi
mostlyclean-generic:

clean-generic:

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
	-test . = "$(srcdir)" || test -z "$(CONFIG_CLEAN_VPATH_FILES)" || rm -f $(CONFIG_CLEAN_VPATH_FILES)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-am

clean-am: clean-binPROGRAMS clean-generic mostlyclean-am

distclean: distclean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-hdr distclean-tags

dvi: dvi-am

dvi-am:

html: html-am

html-am:

info: info-am

info-am:

install-data-am:

install-dvi: install-dvi-am

install-dvi-am:

install-exec-am: install-binPROGRAMS

install-html: install-html-am

install-html-am:

install-info: install-info-am

install-info-am:

install-man:

install-pdf: install-pdf-am

install-pdf-am:

install-ps: install-ps-am

install-ps-am:

installcheck-am:

maintainer-clean: maintainer-clean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf $(top_srcdir)/autom4te.cache
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic

pdf: pdf-am

pdf-am:

ps: ps-am

ps-am:

uninstall-am: uninstall-binPROGRAMS

.MAKE: all install-am install-strip

.PHONY: CTAGS GTAGS all all-am am--refresh check check-am clean \
	clean-binPROGRAMS clean-generic ctags dist dist-all dist-bzip2 \
	dist-gzip dist-lzip dist-lzma dist-shar dist-tarZ dist-xz \
	dist-zip distcheck distclean distclean-compile \
	distclean-generic distclean-hdr distclean-tags distcleancheck \
	distdir distuninstallcheck dvi dvi-am html html-am info \
	info-am install install-am install-binPROGRAMS install-data \
	install-data-am install-dvi install-dvi-am install-exec \
	install-exec-am install-html install-html-am install-info \
	install-info-am install-man install-pdf install-pdf-am \
	install-ps install-ps-am install-strip installcheck \
	installcheck-am installdirs maintainer-clean \
	maintainer-clean-generic mostlyclean mostlyclean-compile \
	mostlyclean-generic pdf pdf-am ps ps-am tags uninstall \
	uninstall-am uninstall-binPROGRAMS


# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
